// Package permission defines the metaxisdata permission catalog.
//
// A permission is a fine-grained string of the form
// "metaxisdata.<resource>.<verb>" (e.g. "metaxisdata.instances.create"). The
// catalog is single-sourced from permission.json: the constants and the
// allPermissions list in permission_gen.go are generated by
// `go generate ./backend/common/permission`. A role is a named bundle of
// permissions (see backend/store/predefined_roles.go and backend/store/role.go),
// and an IAM policy binds principals to roles on the workspace
// (see backend/store/policy.go).
//
// This mirrors laelia's backend/common/permission, adapted to metaxisdata's
// single-workspace domain.
package permission

//go:generate go run ./gen

// Permission is a fine-grained capability string. It is a type alias of string
// so that it can be used as a map key and compared with the raw strings carried
// by the metaxisdata.v1.permission proto annotation.
type Permission = string

// AllPermissions returns a copy of the full permission catalog.
func AllPermissions() []Permission {
	out := make([]Permission, len(allPermissions))
	copy(out, allPermissions)
	return out
}

// Exist reports whether the permission string is a known catalog entry.
func Exist(permission string) bool {
	return allPermissionsMap[permission]
}
