// Code generated by go generate ./backend/common/permission; DO NOT EDIT.

package permission

// Permission constants mirror permission.json; the string is the
// fine-grained capability used by proto annotations and role matrices.
const (
	InstancesGet                       Permission = "metaxisdata.instances.get"
	InstancesList                      Permission = "metaxisdata.instances.list"
	InstancesCreate                    Permission = "metaxisdata.instances.create"
	InstancesUpdate                    Permission = "metaxisdata.instances.update"
	InstancesDelete                    Permission = "metaxisdata.instances.delete"
	InstancesUndelete                  Permission = "metaxisdata.instances.undelete"
	InstancesSync                      Permission = "metaxisdata.instances.sync"
	EnvironmentsList                   Permission = "metaxisdata.environments.list"
	DataSourcesCreate                  Permission = "metaxisdata.dataSources.create"
	DataSourcesUpdate                  Permission = "metaxisdata.dataSources.update"
	DataSourcesDelete                  Permission = "metaxisdata.dataSources.delete"
	DatabasesList                      Permission = "metaxisdata.databases.list"
	DatabasesRead                      Permission = "metaxisdata.databases.read"
	DatabasesSync                      Permission = "metaxisdata.databases.sync"
	ManualSQLsGet                      Permission = "metaxisdata.manualSqls.get"
	ManualSQLsList                     Permission = "metaxisdata.manualSqls.list"
	ManualSQLsCreate                   Permission = "metaxisdata.manualSqls.create"
	ManualSQLsUpdate                   Permission = "metaxisdata.manualSqls.update"
	ManualSQLsDelete                   Permission = "metaxisdata.manualSqls.delete"
	LineageGet                         Permission = "metaxisdata.lineage.get"
	OpenLineageRead                    Permission = "metaxisdata.openlineage.read"
	OpenLineageNamespaceMappingsList   Permission = "metaxisdata.openlineage.namespaceMappings.list"
	OpenLineageNamespaceMappingsCreate Permission = "metaxisdata.openlineage.namespaceMappings.create"
	OpenLineageNamespaceMappingsUpdate Permission = "metaxisdata.openlineage.namespaceMappings.update"
	OpenLineageNamespaceMappingsDelete Permission = "metaxisdata.openlineage.namespaceMappings.delete"
	OpenLineageApiKeysList             Permission = "metaxisdata.openlineage.apiKeys.list"
	OpenLineageApiKeysCreate           Permission = "metaxisdata.openlineage.apiKeys.create"
	OpenLineageApiKeysDelete           Permission = "metaxisdata.openlineage.apiKeys.delete"
	LLMProfilesList                    Permission = "metaxisdata.llm.profiles.list"
	LLMProfilesCreate                  Permission = "metaxisdata.llm.profiles.create"
	LLMProfilesUpdate                  Permission = "metaxisdata.llm.profiles.update"
	LLMProfilesDelete                  Permission = "metaxisdata.llm.profiles.delete"
	LLMProfilesFetchModels             Permission = "metaxisdata.llm.profiles.fetchModels"
	ExplainSQLExplain                  Permission = "metaxisdata.explainSql.explain"
	UsersGet                           Permission = "metaxisdata.users.get"
	UsersList                          Permission = "metaxisdata.users.list"
	UsersCreate                        Permission = "metaxisdata.users.create"
	UsersUpdate                        Permission = "metaxisdata.users.update"
	UsersDelete                        Permission = "metaxisdata.users.delete"
	UsersUndelete                      Permission = "metaxisdata.users.undelete"
	GroupsGet                          Permission = "metaxisdata.groups.get"
	GroupsList                         Permission = "metaxisdata.groups.list"
	GroupsCreate                       Permission = "metaxisdata.groups.create"
	GroupsUpdate                       Permission = "metaxisdata.groups.update"
	GroupsDelete                       Permission = "metaxisdata.groups.delete"
	RolesGet                           Permission = "metaxisdata.roles.get"
	RolesList                          Permission = "metaxisdata.roles.list"
	RolesCreate                        Permission = "metaxisdata.roles.create"
	RolesUpdate                        Permission = "metaxisdata.roles.update"
	RolesDelete                        Permission = "metaxisdata.roles.delete"
	IAMGetPolicy                       Permission = "metaxisdata.iam.getPolicy"
	IAMSetPolicy                       Permission = "metaxisdata.iam.setPolicy"
	SettingsGet                        Permission = "metaxisdata.settings.get"
	SettingsUpdate                     Permission = "metaxisdata.settings.update"
	AuditLogsSearch                    Permission = "metaxisdata.auditLogs.search"
)

// allPermissions is the complete, authoritative list of valid permission
// strings, derived from permission.json. It feeds allPermissionsMap and
// AllPermissions.
var allPermissions = []Permission{
	InstancesGet,
	InstancesList,
	InstancesCreate,
	InstancesUpdate,
	InstancesDelete,
	InstancesUndelete,
	InstancesSync,
	EnvironmentsList,
	DataSourcesCreate,
	DataSourcesUpdate,
	DataSourcesDelete,
	DatabasesList,
	DatabasesRead,
	DatabasesSync,
	ManualSQLsGet,
	ManualSQLsList,
	ManualSQLsCreate,
	ManualSQLsUpdate,
	ManualSQLsDelete,
	LineageGet,
	OpenLineageRead,
	OpenLineageNamespaceMappingsList,
	OpenLineageNamespaceMappingsCreate,
	OpenLineageNamespaceMappingsUpdate,
	OpenLineageNamespaceMappingsDelete,
	OpenLineageApiKeysList,
	OpenLineageApiKeysCreate,
	OpenLineageApiKeysDelete,
	LLMProfilesList,
	LLMProfilesCreate,
	LLMProfilesUpdate,
	LLMProfilesDelete,
	LLMProfilesFetchModels,
	ExplainSQLExplain,
	UsersGet,
	UsersList,
	UsersCreate,
	UsersUpdate,
	UsersDelete,
	UsersUndelete,
	GroupsGet,
	GroupsList,
	GroupsCreate,
	GroupsUpdate,
	GroupsDelete,
	RolesGet,
	RolesList,
	RolesCreate,
	RolesUpdate,
	RolesDelete,
	IAMGetPolicy,
	IAMSetPolicy,
	SettingsGet,
	SettingsUpdate,
	AuditLogsSearch,
}

var allPermissionsMap = func() map[Permission]bool {
	m := make(map[Permission]bool, len(allPermissions))
	for _, p := range allPermissions {
		m[p] = true
	}
	return m
}()
