// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/audit_log_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditLogSeverity int32

const (
	AuditLogSeverity_AUDIT_LOG_SEVERITY_UNSPECIFIED AuditLogSeverity = 0
	AuditLogSeverity_INFO                           AuditLogSeverity = 1
	AuditLogSeverity_WARNING                        AuditLogSeverity = 2
	AuditLogSeverity_ERROR                          AuditLogSeverity = 3
)

// Enum value maps for AuditLogSeverity.
var (
	AuditLogSeverity_name = map[int32]string{
		0: "AUDIT_LOG_SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
	}
	AuditLogSeverity_value = map[string]int32{
		"AUDIT_LOG_SEVERITY_UNSPECIFIED": 0,
		"INFO":                           1,
		"WARNING":                        2,
		"ERROR":                          3,
	}
)

func (x AuditLogSeverity) Enum() *AuditLogSeverity {
	p := new(AuditLogSeverity)
	*p = x
	return p
}

func (x AuditLogSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditLogSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_audit_log_service_proto_enumTypes[0].Descriptor()
}

func (AuditLogSeverity) Type() protoreflect.EnumType {
	return &file_v1_audit_log_service_proto_enumTypes[0]
}

func (x AuditLogSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditLogSeverity.Descriptor instead.
func (AuditLogSeverity) EnumDescriptor() ([]byte, []int) {
	return file_v1_audit_log_service_proto_rawDescGZIP(), []int{0}
}

type AuditLogStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogStatus) Reset() {
	*x = AuditLogStatus{}
	mi := &file_v1_audit_log_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogStatus) ProtoMessage() {}

func (x *AuditLogStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_log_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogStatus.ProtoReflect.Descriptor instead.
func (*AuditLogStatus) Descriptor() ([]byte, []int) {
	return file_v1_audit_log_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLogStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuditLogStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuditRequestMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequestMetadata) Reset() {
	*x = AuditRequestMetadata{}
	mi := &file_v1_audit_log_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequestMetadata) ProtoMessage() {}

func (x *AuditRequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_log_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequestMetadata.ProtoReflect.Descriptor instead.
func (*AuditRequestMetadata) Descriptor() ([]byte, []int) {
	return file_v1_audit_log_service_proto_rawDescGZIP(), []int{1}
}

func (x *AuditRequestMetadata) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditRequestMetadata) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type AuditLog struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Parent          string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Method          string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Resource        string                 `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	User            string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Severity        AuditLogSeverity       `protobuf:"varint,7,opt,name=severity,proto3,enum=metaxisdata.v1.AuditLogSeverity" json:"severity,omitempty"`
	Request         *structpb.Struct       `protobuf:"bytes,8,opt,name=request,proto3" json:"request,omitempty"`
	Response        *structpb.Struct       `protobuf:"bytes,9,opt,name=response,proto3" json:"response,omitempty"`
	Status          *AuditLogStatus        `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs       int64                  `protobuf:"varint,11,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ServiceData     *structpb.Struct       `protobuf:"bytes,12,opt,name=service_data,json=serviceData,proto3" json:"service_data,omitempty"`
	RequestMetadata *AuditRequestMetadata  `protobuf:"bytes,13,opt,name=request_metadata,json=requestMetadata,proto3" json:"request_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_v1_audit_log_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_log_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_v1_audit_log_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuditLog) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *AuditLog) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *AuditLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuditLog) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditLog) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuditLog) GetSeverity() AuditLogSeverity {
	if x != nil {
		return x.Severity
	}
	return AuditLogSeverity_AUDIT_LOG_SEVERITY_UNSPECIFIED
}

func (x *AuditLog) GetRequest() *structpb.Struct {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuditLog) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AuditLog) GetStatus() *AuditLogStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AuditLog) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AuditLog) GetServiceData() *structpb.Struct {
	if x != nil {
		return x.ServiceData
	}
	return nil
}

func (x *AuditLog) GetRequestMetadata() *AuditRequestMetadata {
	if x != nil {
		return x.RequestMetadata
	}
	return nil
}

type ListAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsRequest) Reset() {
	*x = ListAuditLogsRequest{}
	mi := &file_v1_audit_log_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsRequest) ProtoMessage() {}

func (x *ListAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_log_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_v1_audit_log_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAuditLogsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListAuditLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuditLogsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuditLogsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditLogs     []*AuditLog            `protobuf:"bytes,1,rep,name=audit_logs,json=auditLogs,proto3" json:"audit_logs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogsResponse) Reset() {
	*x = ListAuditLogsResponse{}
	mi := &file_v1_audit_log_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogsResponse) ProtoMessage() {}

func (x *ListAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_audit_log_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_v1_audit_log_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAuditLogsResponse) GetAuditLogs() []*AuditLog {
	if x != nil {
		return x.AuditLogs
	}
	return nil
}

func (x *ListAuditLogsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_v1_audit_log_service_proto protoreflect.FileDescriptor

const file_v1_audit_log_service_proto_rawDesc = "" +
	"\n" +
	"\x1av1/audit_log_service.proto\x12\x0emetaxisdata.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x0eAuditLogStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x14AuditRequestMetadata\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"\xc5\x04\n" +
	"\bAuditLog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\vcreate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12<\n" +
	"\bseverity\x18\a \x01(\x0e2 .metaxisdata.v1.AuditLogSeverityR\bseverity\x121\n" +
	"\arequest\x18\b \x01(\v2\x17.google.protobuf.StructR\arequest\x123\n" +
	"\bresponse\x18\t \x01(\v2\x17.google.protobuf.StructR\bresponse\x126\n" +
	"\x06status\x18\n" +
	" \x01(\v2\x1e.metaxisdata.v1.AuditLogStatusR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\v \x01(\x03R\tlatencyMs\x12:\n" +
	"\fservice_data\x18\f \x01(\v2\x17.google.protobuf.StructR\vserviceData\x12O\n" +
	"\x10request_metadata\x18\r \x01(\v2$.metaxisdata.v1.AuditRequestMetadataR\x0frequestMetadata\"\x82\x01\n" +
	"\x14ListAuditLogsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"x\n" +
	"\x15ListAuditLogsResponse\x127\n" +
	"\n" +
	"audit_logs\x18\x01 \x03(\v2\x18.metaxisdata.v1.AuditLogR\tauditLogs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*X\n" +
	"\x10AuditLogSeverity\x12\"\n" +
	"\x1eAUDIT_LOG_SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\x9c\x01\n" +
	"\x0fAuditLogService\x12\x88\x01\n" +
	"\rListAuditLogs\x12$.metaxisdata.v1.ListAuditLogsRequest\x1a%.metaxisdata.v1.ListAuditLogsResponse\"*\xdaA\x06parent\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/{parent=**}/auditLogsB6Z4github.com/Ranxy/metaxisdata/backend/generated-go/v1b\x06proto3"

var (
	file_v1_audit_log_service_proto_rawDescOnce sync.Once
	file_v1_audit_log_service_proto_rawDescData []byte
)

func file_v1_audit_log_service_proto_rawDescGZIP() []byte {
	file_v1_audit_log_service_proto_rawDescOnce.Do(func() {
		file_v1_audit_log_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_audit_log_service_proto_rawDesc), len(file_v1_audit_log_service_proto_rawDesc)))
	})
	return file_v1_audit_log_service_proto_rawDescData
}

var file_v1_audit_log_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_audit_log_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_audit_log_service_proto_goTypes = []any{
	(AuditLogSeverity)(0),         // 0: metaxisdata.v1.AuditLogSeverity
	(*AuditLogStatus)(nil),        // 1: metaxisdata.v1.AuditLogStatus
	(*AuditRequestMetadata)(nil),  // 2: metaxisdata.v1.AuditRequestMetadata
	(*AuditLog)(nil),              // 3: metaxisdata.v1.AuditLog
	(*ListAuditLogsRequest)(nil),  // 4: metaxisdata.v1.ListAuditLogsRequest
	(*ListAuditLogsResponse)(nil), // 5: metaxisdata.v1.ListAuditLogsResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
}
var file_v1_audit_log_service_proto_depIdxs = []int32{
	6, // 0: metaxisdata.v1.AuditLog.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: metaxisdata.v1.AuditLog.severity:type_name -> metaxisdata.v1.AuditLogSeverity
	7, // 2: metaxisdata.v1.AuditLog.request:type_name -> google.protobuf.Struct
	7, // 3: metaxisdata.v1.AuditLog.response:type_name -> google.protobuf.Struct
	1, // 4: metaxisdata.v1.AuditLog.status:type_name -> metaxisdata.v1.AuditLogStatus
	7, // 5: metaxisdata.v1.AuditLog.service_data:type_name -> google.protobuf.Struct
	2, // 6: metaxisdata.v1.AuditLog.request_metadata:type_name -> metaxisdata.v1.AuditRequestMetadata
	3, // 7: metaxisdata.v1.ListAuditLogsResponse.audit_logs:type_name -> metaxisdata.v1.AuditLog
	4, // 8: metaxisdata.v1.AuditLogService.ListAuditLogs:input_type -> metaxisdata.v1.ListAuditLogsRequest
	5, // 9: metaxisdata.v1.AuditLogService.ListAuditLogs:output_type -> metaxisdata.v1.ListAuditLogsResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_v1_audit_log_service_proto_init() }
func file_v1_audit_log_service_proto_init() {
	if File_v1_audit_log_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_audit_log_service_proto_rawDesc), len(file_v1_audit_log_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_audit_log_service_proto_goTypes,
		DependencyIndexes: file_v1_audit_log_service_proto_depIdxs,
		EnumInfos:         file_v1_audit_log_service_proto_enumTypes,
		MessageInfos:      file_v1_audit_log_service_proto_msgTypes,
	}.Build()
	File_v1_audit_log_service_proto = out.File
	file_v1_audit_log_service_proto_goTypes = nil
	file_v1_audit_log_service_proto_depIdxs = nil
}
