// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/iam_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IamService_GetWorkspaceIamPolicy_FullMethodName = "/metaxisdata.v1.IamService/GetWorkspaceIamPolicy"
	IamService_SetWorkspaceIamPolicy_FullMethodName = "/metaxisdata.v1.IamService/SetWorkspaceIamPolicy"
)

// IamServiceClient is the client API for IamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IamService exposes the workspace IAM policy for management. Get reads the
// whole policy; Set replaces it whole, guarded by the etag. Both RPCs are gated
// by metaxisdata.iam.getPolicy / metaxisdata.iam.setPolicy.
type IamServiceClient interface {
	// Get the workspace IAM policy.
	GetWorkspaceIamPolicy(ctx context.Context, in *GetWorkspaceIamPolicyRequest, opts ...grpc.CallOption) (*IamPolicyView, error)
	// Set the workspace IAM policy (full replace, etag-guarded).
	SetWorkspaceIamPolicy(ctx context.Context, in *SetWorkspaceIamPolicyRequest, opts ...grpc.CallOption) (*IamPolicyView, error)
}

type iamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIamServiceClient(cc grpc.ClientConnInterface) IamServiceClient {
	return &iamServiceClient{cc}
}

func (c *iamServiceClient) GetWorkspaceIamPolicy(ctx context.Context, in *GetWorkspaceIamPolicyRequest, opts ...grpc.CallOption) (*IamPolicyView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IamPolicyView)
	err := c.cc.Invoke(ctx, IamService_GetWorkspaceIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamServiceClient) SetWorkspaceIamPolicy(ctx context.Context, in *SetWorkspaceIamPolicyRequest, opts ...grpc.CallOption) (*IamPolicyView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IamPolicyView)
	err := c.cc.Invoke(ctx, IamService_SetWorkspaceIamPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IamServiceServer is the server API for IamService service.
// All implementations must embed UnimplementedIamServiceServer
// for forward compatibility.
//
// IamService exposes the workspace IAM policy for management. Get reads the
// whole policy; Set replaces it whole, guarded by the etag. Both RPCs are gated
// by metaxisdata.iam.getPolicy / metaxisdata.iam.setPolicy.
type IamServiceServer interface {
	// Get the workspace IAM policy.
	GetWorkspaceIamPolicy(context.Context, *GetWorkspaceIamPolicyRequest) (*IamPolicyView, error)
	// Set the workspace IAM policy (full replace, etag-guarded).
	SetWorkspaceIamPolicy(context.Context, *SetWorkspaceIamPolicyRequest) (*IamPolicyView, error)
	mustEmbedUnimplementedIamServiceServer()
}

// UnimplementedIamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIamServiceServer struct{}

func (UnimplementedIamServiceServer) GetWorkspaceIamPolicy(context.Context, *GetWorkspaceIamPolicyRequest) (*IamPolicyView, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkspaceIamPolicy not implemented")
}
func (UnimplementedIamServiceServer) SetWorkspaceIamPolicy(context.Context, *SetWorkspaceIamPolicyRequest) (*IamPolicyView, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWorkspaceIamPolicy not implemented")
}
func (UnimplementedIamServiceServer) mustEmbedUnimplementedIamServiceServer() {}
func (UnimplementedIamServiceServer) testEmbeddedByValue()                    {}

// UnsafeIamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IamServiceServer will
// result in compilation errors.
type UnsafeIamServiceServer interface {
	mustEmbedUnimplementedIamServiceServer()
}

func RegisterIamServiceServer(s grpc.ServiceRegistrar, srv IamServiceServer) {
	// If the following call panics, it indicates UnimplementedIamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IamService_ServiceDesc, srv)
}

func _IamService_GetWorkspaceIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).GetWorkspaceIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_GetWorkspaceIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).GetWorkspaceIamPolicy(ctx, req.(*GetWorkspaceIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamService_SetWorkspaceIamPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWorkspaceIamPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamServiceServer).SetWorkspaceIamPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamService_SetWorkspaceIamPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamServiceServer).SetWorkspaceIamPolicy(ctx, req.(*SetWorkspaceIamPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IamService_ServiceDesc is the grpc.ServiceDesc for IamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metaxisdata.v1.IamService",
	HandlerType: (*IamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkspaceIamPolicy",
			Handler:    _IamService_GetWorkspaceIamPolicy_Handler,
		},
		{
			MethodName: "SetWorkspaceIamPolicy",
			Handler:    _IamService_SetWorkspaceIamPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/iam_service.proto",
}
