// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/lineage_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LineageType int32

const (
	LineageType_LINEAGE_TYPE_UNSPECIFIED LineageType = 0
	LineageType_SOURCE                   LineageType = 1
	LineageType_TARGET                   LineageType = 2
)

// Enum value maps for LineageType.
var (
	LineageType_name = map[int32]string{
		0: "LINEAGE_TYPE_UNSPECIFIED",
		1: "SOURCE",
		2: "TARGET",
	}
	LineageType_value = map[string]int32{
		"LINEAGE_TYPE_UNSPECIFIED": 0,
		"SOURCE":                   1,
		"TARGET":                   2,
	}
)

func (x LineageType) Enum() *LineageType {
	p := new(LineageType)
	*p = x
	return p
}

func (x LineageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LineageType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_lineage_service_proto_enumTypes[0].Descriptor()
}

func (LineageType) Type() protoreflect.EnumType {
	return &file_v1_lineage_service_proto_enumTypes[0]
}

func (x LineageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LineageType.Descriptor instead.
func (LineageType) EnumDescriptor() ([]byte, []int) {
	return file_v1_lineage_service_proto_rawDescGZIP(), []int{0}
}

type RelationType int32

const (
	RelationType_RELATION_TYPE_UNSPECIFIED RelationType = 0
	// DIRECT means the source column is directly used in the target column without transformation. For example: select source_column as target_column from table.
	RelationType_DIRECT RelationType = 1
	// INDIRECT means the source column is used in the target column with transformation. For example: select concat(source_column, 'abc') as target_column
	RelationType_INDIRECT RelationType = 2
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "RELATION_TYPE_UNSPECIFIED",
		1: "DIRECT",
		2: "INDIRECT",
	}
	RelationType_value = map[string]int32{
		"RELATION_TYPE_UNSPECIFIED": 0,
		"DIRECT":                    1,
		"INDIRECT":                  2,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_lineage_service_proto_enumTypes[1].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_v1_lineage_service_proto_enumTypes[1]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_v1_lineage_service_proto_rawDescGZIP(), []int{1}
}

type LineageRelation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MetaGuid       string                 `protobuf:"bytes,2,opt,name=meta_guid,json=metaGuid,proto3" json:"meta_guid,omitempty"`
	MetaType       MetaType               `protobuf:"varint,3,opt,name=meta_type,json=metaType,proto3,enum=metaxisdata.v1.MetaType" json:"meta_type,omitempty"`
	SourceGuid     string                 `protobuf:"bytes,4,opt,name=source_guid,json=sourceGuid,proto3" json:"source_guid,omitempty"`
	SourceColumn   string                 `protobuf:"bytes,5,opt,name=source_column,json=sourceColumn,proto3" json:"source_column,omitempty"`
	TargetGuid     string                 `protobuf:"bytes,6,opt,name=target_guid,json=targetGuid,proto3" json:"target_guid,omitempty"`
	TargetColumn   string                 `protobuf:"bytes,7,opt,name=target_column,json=targetColumn,proto3" json:"target_column,omitempty"`
	RelationType   RelationType           `protobuf:"varint,8,opt,name=relation_type,json=relationType,proto3,enum=metaxisdata.v1.RelationType" json:"relation_type,omitempty"`
	Transformation string                 `protobuf:"bytes,9,opt,name=transformation,proto3" json:"transformation,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LineageRelation) Reset() {
	*x = LineageRelation{}
	mi := &file_v1_lineage_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineageRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineageRelation) ProtoMessage() {}

func (x *LineageRelation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_lineage_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineageRelation.ProtoReflect.Descriptor instead.
func (*LineageRelation) Descriptor() ([]byte, []int) {
	return file_v1_lineage_service_proto_rawDescGZIP(), []int{0}
}

func (x *LineageRelation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LineageRelation) GetMetaGuid() string {
	if x != nil {
		return x.MetaGuid
	}
	return ""
}

func (x *LineageRelation) GetMetaType() MetaType {
	if x != nil {
		return x.MetaType
	}
	return MetaType_UNSPECIFIED
}

func (x *LineageRelation) GetSourceGuid() string {
	if x != nil {
		return x.SourceGuid
	}
	return ""
}

func (x *LineageRelation) GetSourceColumn() string {
	if x != nil {
		return x.SourceColumn
	}
	return ""
}

func (x *LineageRelation) GetTargetGuid() string {
	if x != nil {
		return x.TargetGuid
	}
	return ""
}

func (x *LineageRelation) GetTargetColumn() string {
	if x != nil {
		return x.TargetColumn
	}
	return ""
}

func (x *LineageRelation) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (x *LineageRelation) GetTransformation() string {
	if x != nil {
		return x.Transformation
	}
	return ""
}

func (x *LineageRelation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLineageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The global unique id for metadata
	// table: "instance_1;db2;schema3;table4"
	Guid     string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	MetaType MetaType `protobuf:"varint,2,opt,name=meta_type,json=metaType,proto3,enum=metaxisdata.v1.MetaType" json:"meta_type,omitempty"`
	// The lineage type to query, source or target. If not specified, both source and target lineage will be returned.
	LineageType   LineageType `protobuf:"varint,3,opt,name=lineage_type,json=lineageType,proto3,enum=metaxisdata.v1.LineageType" json:"lineage_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLineageRequest) Reset() {
	*x = GetLineageRequest{}
	mi := &file_v1_lineage_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLineageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLineageRequest) ProtoMessage() {}

func (x *GetLineageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_lineage_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLineageRequest.ProtoReflect.Descriptor instead.
func (*GetLineageRequest) Descriptor() ([]byte, []int) {
	return file_v1_lineage_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetLineageRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *GetLineageRequest) GetMetaType() MetaType {
	if x != nil {
		return x.MetaType
	}
	return MetaType_UNSPECIFIED
}

func (x *GetLineageRequest) GetLineageType() LineageType {
	if x != nil {
		return x.LineageType
	}
	return LineageType_LINEAGE_TYPE_UNSPECIFIED
}

type GetLineageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of lineage relations for the given metadata.
	Relations     []*LineageRelation `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLineageResponse) Reset() {
	*x = GetLineageResponse{}
	mi := &file_v1_lineage_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLineageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLineageResponse) ProtoMessage() {}

func (x *GetLineageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_lineage_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLineageResponse.ProtoReflect.Descriptor instead.
func (*GetLineageResponse) Descriptor() ([]byte, []int) {
	return file_v1_lineage_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLineageResponse) GetRelations() []*LineageRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type GetLineageForContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The global unique id for metadata
	// view: "instance_1;db2;schema3;view1"
	Guid          string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	MetaType      MetaType `protobuf:"varint,2,opt,name=meta_type,json=metaType,proto3,enum=metaxisdata.v1.MetaType" json:"meta_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLineageForContextRequest) Reset() {
	*x = GetLineageForContextRequest{}
	mi := &file_v1_lineage_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLineageForContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLineageForContextRequest) ProtoMessage() {}

func (x *GetLineageForContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_lineage_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLineageForContextRequest.ProtoReflect.Descriptor instead.
func (*GetLineageForContextRequest) Descriptor() ([]byte, []int) {
	return file_v1_lineage_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLineageForContextRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *GetLineageForContextRequest) GetMetaType() MetaType {
	if x != nil {
		return x.MetaType
	}
	return MetaType_UNSPECIFIED
}

type GetLineageForContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of lineage relations for the given metadata.
	Relations     []*LineageRelation `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLineageForContextResponse) Reset() {
	*x = GetLineageForContextResponse{}
	mi := &file_v1_lineage_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLineageForContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLineageForContextResponse) ProtoMessage() {}

func (x *GetLineageForContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_lineage_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLineageForContextResponse.ProtoReflect.Descriptor instead.
func (*GetLineageForContextResponse) Descriptor() ([]byte, []int) {
	return file_v1_lineage_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetLineageForContextResponse) GetRelations() []*LineageRelation {
	if x != nil {
		return x.Relations
	}
	return nil
}

var File_v1_lineage_service_proto protoreflect.FileDescriptor

const file_v1_lineage_service_proto_rawDesc = "" +
	"\n" +
	"\x18v1/lineage_service.proto\x12\x0emetaxisdata.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fv1/common.proto\x1a\x19v1/database_service.proto\"\xa7\x03\n" +
	"\x0fLineageRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmeta_guid\x18\x02 \x01(\tR\bmetaGuid\x125\n" +
	"\tmeta_type\x18\x03 \x01(\x0e2\x18.metaxisdata.v1.MetaTypeR\bmetaType\x12\x1f\n" +
	"\vsource_guid\x18\x04 \x01(\tR\n" +
	"sourceGuid\x12#\n" +
	"\rsource_column\x18\x05 \x01(\tR\fsourceColumn\x12\x1f\n" +
	"\vtarget_guid\x18\x06 \x01(\tR\n" +
	"targetGuid\x12#\n" +
	"\rtarget_column\x18\a \x01(\tR\ftargetColumn\x12A\n" +
	"\rrelation_type\x18\b \x01(\x0e2\x1c.metaxisdata.v1.RelationTypeR\frelationType\x12&\n" +
	"\x0etransformation\x18\t \x01(\tR\x0etransformation\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc4\x01\n" +
	"\x11GetLineageRequest\x128\n" +
	"\x04guid\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n" +
	"\x1cmetaxisdata/DatabaseMetadataR\x04guid\x125\n" +
	"\tmeta_type\x18\x02 \x01(\x0e2\x18.metaxisdata.v1.MetaTypeR\bmetaType\x12>\n" +
	"\flineage_type\x18\x03 \x01(\x0e2\x1b.metaxisdata.v1.LineageTypeR\vlineageType\"S\n" +
	"\x12GetLineageResponse\x12=\n" +
	"\trelations\x18\x01 \x03(\v2\x1f.metaxisdata.v1.LineageRelationR\trelations\"\x8e\x01\n" +
	"\x1bGetLineageForContextRequest\x128\n" +
	"\x04guid\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n" +
	"\x1cmetaxisdata/DatabaseMetadataR\x04guid\x125\n" +
	"\tmeta_type\x18\x02 \x01(\x0e2\x18.metaxisdata.v1.MetaTypeR\bmetaType\"]\n" +
	"\x1cGetLineageForContextResponse\x12=\n" +
	"\trelations\x18\x01 \x03(\v2\x1f.metaxisdata.v1.LineageRelationR\trelations*C\n" +
	"\vLineageType\x12\x1c\n" +
	"\x18LINEAGE_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06SOURCE\x10\x01\x12\n" +
	"\n" +
	"\x06TARGET\x10\x02*G\n" +
	"\fRelationType\x12\x1d\n" +
	"\x19RELATION_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x01\x12\f\n" +
	"\bINDIRECT\x10\x022\x9f\x02\n" +
	"\x0eLineageService\x12r\n" +
	"\n" +
	"GetLineage\x12!.metaxisdata.v1.GetLineageRequest\x1a\".metaxisdata.v1.GetLineageResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/{guid=lineages/*}\x12\x98\x01\n" +
	"\x14GetLineageForContext\x12+.metaxisdata.v1.GetLineageForContextRequest\x1a,.metaxisdata.v1.GetLineageForContextResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/context/{guid=lineages/*}B6Z4github.com/Ranxy/metaxisdata/backend/generated-go/v1b\x06proto3"

var (
	file_v1_lineage_service_proto_rawDescOnce sync.Once
	file_v1_lineage_service_proto_rawDescData []byte
)

func file_v1_lineage_service_proto_rawDescGZIP() []byte {
	file_v1_lineage_service_proto_rawDescOnce.Do(func() {
		file_v1_lineage_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_lineage_service_proto_rawDesc), len(file_v1_lineage_service_proto_rawDesc)))
	})
	return file_v1_lineage_service_proto_rawDescData
}

var file_v1_lineage_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_lineage_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_lineage_service_proto_goTypes = []any{
	(LineageType)(0),                     // 0: metaxisdata.v1.LineageType
	(RelationType)(0),                    // 1: metaxisdata.v1.RelationType
	(*LineageRelation)(nil),              // 2: metaxisdata.v1.LineageRelation
	(*GetLineageRequest)(nil),            // 3: metaxisdata.v1.GetLineageRequest
	(*GetLineageResponse)(nil),           // 4: metaxisdata.v1.GetLineageResponse
	(*GetLineageForContextRequest)(nil),  // 5: metaxisdata.v1.GetLineageForContextRequest
	(*GetLineageForContextResponse)(nil), // 6: metaxisdata.v1.GetLineageForContextResponse
	(MetaType)(0),                        // 7: metaxisdata.v1.MetaType
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
}
var file_v1_lineage_service_proto_depIdxs = []int32{
	7,  // 0: metaxisdata.v1.LineageRelation.meta_type:type_name -> metaxisdata.v1.MetaType
	1,  // 1: metaxisdata.v1.LineageRelation.relation_type:type_name -> metaxisdata.v1.RelationType
	8,  // 2: metaxisdata.v1.LineageRelation.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 3: metaxisdata.v1.GetLineageRequest.meta_type:type_name -> metaxisdata.v1.MetaType
	0,  // 4: metaxisdata.v1.GetLineageRequest.lineage_type:type_name -> metaxisdata.v1.LineageType
	2,  // 5: metaxisdata.v1.GetLineageResponse.relations:type_name -> metaxisdata.v1.LineageRelation
	7,  // 6: metaxisdata.v1.GetLineageForContextRequest.meta_type:type_name -> metaxisdata.v1.MetaType
	2,  // 7: metaxisdata.v1.GetLineageForContextResponse.relations:type_name -> metaxisdata.v1.LineageRelation
	3,  // 8: metaxisdata.v1.LineageService.GetLineage:input_type -> metaxisdata.v1.GetLineageRequest
	5,  // 9: metaxisdata.v1.LineageService.GetLineageForContext:input_type -> metaxisdata.v1.GetLineageForContextRequest
	4,  // 10: metaxisdata.v1.LineageService.GetLineage:output_type -> metaxisdata.v1.GetLineageResponse
	6,  // 11: metaxisdata.v1.LineageService.GetLineageForContext:output_type -> metaxisdata.v1.GetLineageForContextResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_lineage_service_proto_init() }
func file_v1_lineage_service_proto_init() {
	if File_v1_lineage_service_proto != nil {
		return
	}
	file_v1_common_proto_init()
	file_v1_database_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_lineage_service_proto_rawDesc), len(file_v1_lineage_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_lineage_service_proto_goTypes,
		DependencyIndexes: file_v1_lineage_service_proto_depIdxs,
		EnumInfos:         file_v1_lineage_service_proto_enumTypes,
		MessageInfos:      file_v1_lineage_service_proto_msgTypes,
	}.Build()
	File_v1_lineage_service_proto = out.File
	file_v1_lineage_service_proto_goTypes = nil
	file_v1_lineage_service_proto_depIdxs = nil
}
