// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/openlineage_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenLineageDatasetScope int32

const (
	OpenLineageDatasetScope_OPENLINEAGE_DATASET_SCOPE_UNSPECIFIED OpenLineageDatasetScope = 0
	OpenLineageDatasetScope_OPENLINEAGE_DATASET_SCOPE_ALL         OpenLineageDatasetScope = 1
	OpenLineageDatasetScope_OPENLINEAGE_DATASET_SCOPE_INTERNAL    OpenLineageDatasetScope = 2
	OpenLineageDatasetScope_OPENLINEAGE_DATASET_SCOPE_EXTERNAL    OpenLineageDatasetScope = 3
)

// Enum value maps for OpenLineageDatasetScope.
var (
	OpenLineageDatasetScope_name = map[int32]string{
		0: "OPENLINEAGE_DATASET_SCOPE_UNSPECIFIED",
		1: "OPENLINEAGE_DATASET_SCOPE_ALL",
		2: "OPENLINEAGE_DATASET_SCOPE_INTERNAL",
		3: "OPENLINEAGE_DATASET_SCOPE_EXTERNAL",
	}
	OpenLineageDatasetScope_value = map[string]int32{
		"OPENLINEAGE_DATASET_SCOPE_UNSPECIFIED": 0,
		"OPENLINEAGE_DATASET_SCOPE_ALL":         1,
		"OPENLINEAGE_DATASET_SCOPE_INTERNAL":    2,
		"OPENLINEAGE_DATASET_SCOPE_EXTERNAL":    3,
	}
)

func (x OpenLineageDatasetScope) Enum() *OpenLineageDatasetScope {
	p := new(OpenLineageDatasetScope)
	*p = x
	return p
}

func (x OpenLineageDatasetScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenLineageDatasetScope) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_openlineage_service_proto_enumTypes[0].Descriptor()
}

func (OpenLineageDatasetScope) Type() protoreflect.EnumType {
	return &file_v1_openlineage_service_proto_enumTypes[0]
}

func (x OpenLineageDatasetScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenLineageDatasetScope.Descriptor instead.
func (OpenLineageDatasetScope) EnumDescriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{0}
}

type NamespaceMapping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the namespace mapping.
	// Format: openlineage/namespaceMappings/{namespace_mapping}
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace          string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	InstanceResourceId string                 `protobuf:"bytes,3,opt,name=instance_resource_id,json=instanceResourceId,proto3" json:"instance_resource_id,omitempty"`
	DatabaseName       string                 `protobuf:"bytes,4,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NamespaceMapping) Reset() {
	*x = NamespaceMapping{}
	mi := &file_v1_openlineage_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceMapping) ProtoMessage() {}

func (x *NamespaceMapping) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceMapping.ProtoReflect.Descriptor instead.
func (*NamespaceMapping) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{0}
}

func (x *NamespaceMapping) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceMapping) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespaceMapping) GetInstanceResourceId() string {
	if x != nil {
		return x.InstanceResourceId
	}
	return ""
}

func (x *NamespaceMapping) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *NamespaceMapping) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NamespaceMapping) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OpenLineageRun struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the run.
	// Format: openlineage/runs/{guid}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The run identifier, equal to the last segment of `name`.
	Guid               string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	TaskGuid           string                 `protobuf:"bytes,3,opt,name=task_guid,json=taskGuid,proto3" json:"task_guid,omitempty"`
	RunId              string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	JobNamespace       string                 `protobuf:"bytes,5,opt,name=job_namespace,json=jobNamespace,proto3" json:"job_namespace,omitempty"`
	JobName            string                 `protobuf:"bytes,6,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType            string                 `protobuf:"bytes,7,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	EventType          string                 `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventTime          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	Producer           string                 `protobuf:"bytes,10,opt,name=producer,proto3" json:"producer,omitempty"`
	Source             string                 `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	Integration        string                 `protobuf:"bytes,12,opt,name=integration,proto3" json:"integration,omitempty"`
	ProcessingType     string                 `protobuf:"bytes,13,opt,name=processing_type,json=processingType,proto3" json:"processing_type,omitempty"`
	ParentJobNamespace string                 `protobuf:"bytes,14,opt,name=parent_job_namespace,json=parentJobNamespace,proto3" json:"parent_job_namespace,omitempty"`
	ParentJobName      string                 `protobuf:"bytes,15,opt,name=parent_job_name,json=parentJobName,proto3" json:"parent_job_name,omitempty"`
	ParentRunId        string                 `protobuf:"bytes,16,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	RootJobNamespace   string                 `protobuf:"bytes,17,opt,name=root_job_namespace,json=rootJobNamespace,proto3" json:"root_job_namespace,omitempty"`
	RootJobName        string                 `protobuf:"bytes,18,opt,name=root_job_name,json=rootJobName,proto3" json:"root_job_name,omitempty"`
	RootRunId          string                 `protobuf:"bytes,19,opt,name=root_run_id,json=rootRunId,proto3" json:"root_run_id,omitempty"`
	InputCount         int32                  `protobuf:"varint,20,opt,name=input_count,json=inputCount,proto3" json:"input_count,omitempty"`
	OutputCount        int32                  `protobuf:"varint,21,opt,name=output_count,json=outputCount,proto3" json:"output_count,omitempty"`
	HasLineage         bool                   `protobuf:"varint,22,opt,name=has_lineage,json=hasLineage,proto3" json:"has_lineage,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// The OpenLineage event as JSON text, exactly as it was received and stored
	// in the `raw_payload` JSONB column.
	RawPayload       string `protobuf:"bytes,25,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	AirflowDagUrl    string `protobuf:"bytes,26,opt,name=airflow_dag_url,json=airflowDagUrl,proto3" json:"airflow_dag_url,omitempty"`
	AirflowRunLogUrl string `protobuf:"bytes,27,opt,name=airflow_run_log_url,json=airflowRunLogUrl,proto3" json:"airflow_run_log_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OpenLineageRun) Reset() {
	*x = OpenLineageRun{}
	mi := &file_v1_openlineage_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenLineageRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenLineageRun) ProtoMessage() {}

func (x *OpenLineageRun) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenLineageRun.ProtoReflect.Descriptor instead.
func (*OpenLineageRun) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{1}
}

func (x *OpenLineageRun) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenLineageRun) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *OpenLineageRun) GetTaskGuid() string {
	if x != nil {
		return x.TaskGuid
	}
	return ""
}

func (x *OpenLineageRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *OpenLineageRun) GetJobNamespace() string {
	if x != nil {
		return x.JobNamespace
	}
	return ""
}

func (x *OpenLineageRun) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *OpenLineageRun) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *OpenLineageRun) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OpenLineageRun) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *OpenLineageRun) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *OpenLineageRun) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OpenLineageRun) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *OpenLineageRun) GetProcessingType() string {
	if x != nil {
		return x.ProcessingType
	}
	return ""
}

func (x *OpenLineageRun) GetParentJobNamespace() string {
	if x != nil {
		return x.ParentJobNamespace
	}
	return ""
}

func (x *OpenLineageRun) GetParentJobName() string {
	if x != nil {
		return x.ParentJobName
	}
	return ""
}

func (x *OpenLineageRun) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

func (x *OpenLineageRun) GetRootJobNamespace() string {
	if x != nil {
		return x.RootJobNamespace
	}
	return ""
}

func (x *OpenLineageRun) GetRootJobName() string {
	if x != nil {
		return x.RootJobName
	}
	return ""
}

func (x *OpenLineageRun) GetRootRunId() string {
	if x != nil {
		return x.RootRunId
	}
	return ""
}

func (x *OpenLineageRun) GetInputCount() int32 {
	if x != nil {
		return x.InputCount
	}
	return 0
}

func (x *OpenLineageRun) GetOutputCount() int32 {
	if x != nil {
		return x.OutputCount
	}
	return 0
}

func (x *OpenLineageRun) GetHasLineage() bool {
	if x != nil {
		return x.HasLineage
	}
	return false
}

func (x *OpenLineageRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OpenLineageRun) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *OpenLineageRun) GetRawPayload() string {
	if x != nil {
		return x.RawPayload
	}
	return ""
}

func (x *OpenLineageRun) GetAirflowDagUrl() string {
	if x != nil {
		return x.AirflowDagUrl
	}
	return ""
}

func (x *OpenLineageRun) GetAirflowRunLogUrl() string {
	if x != nil {
		return x.AirflowRunLogUrl
	}
	return ""
}

type OpenLineageTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the task.
	// Format: openlineage/tasks/{guid}
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The task identifier, equal to the last segment of `name`.
	Guid               string                 `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	JobNamespace       string                 `protobuf:"bytes,3,opt,name=job_namespace,json=jobNamespace,proto3" json:"job_namespace,omitempty"`
	JobName            string                 `protobuf:"bytes,4,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType            string                 `protobuf:"bytes,5,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Integration        string                 `protobuf:"bytes,6,opt,name=integration,proto3" json:"integration,omitempty"`
	ProcessingType     string                 `protobuf:"bytes,7,opt,name=processing_type,json=processingType,proto3" json:"processing_type,omitempty"`
	ParentJobNamespace string                 `protobuf:"bytes,8,opt,name=parent_job_namespace,json=parentJobNamespace,proto3" json:"parent_job_namespace,omitempty"`
	ParentJobName      string                 `protobuf:"bytes,9,opt,name=parent_job_name,json=parentJobName,proto3" json:"parent_job_name,omitempty"`
	RootJobNamespace   string                 `protobuf:"bytes,10,opt,name=root_job_namespace,json=rootJobNamespace,proto3" json:"root_job_namespace,omitempty"`
	RootJobName        string                 `protobuf:"bytes,11,opt,name=root_job_name,json=rootJobName,proto3" json:"root_job_name,omitempty"`
	LatestRunGuid      string                 `protobuf:"bytes,12,opt,name=latest_run_guid,json=latestRunGuid,proto3" json:"latest_run_guid,omitempty"`
	LatestRunId        string                 `protobuf:"bytes,13,opt,name=latest_run_id,json=latestRunId,proto3" json:"latest_run_id,omitempty"`
	LatestEventTime    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=latest_event_time,json=latestEventTime,proto3" json:"latest_event_time,omitempty"`
	LatestProducer     string                 `protobuf:"bytes,15,opt,name=latest_producer,json=latestProducer,proto3" json:"latest_producer,omitempty"`
	LatestSource       string                 `protobuf:"bytes,16,opt,name=latest_source,json=latestSource,proto3" json:"latest_source,omitempty"`
	RunCount           int32                  `protobuf:"varint,17,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	LineageRunCount    int32                  `protobuf:"varint,18,opt,name=lineage_run_count,json=lineageRunCount,proto3" json:"lineage_run_count,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AirflowDagUrl      string                 `protobuf:"bytes,21,opt,name=airflow_dag_url,json=airflowDagUrl,proto3" json:"airflow_dag_url,omitempty"`
	LatestEventType    string                 `protobuf:"bytes,22,opt,name=latest_event_type,json=latestEventType,proto3" json:"latest_event_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OpenLineageTask) Reset() {
	*x = OpenLineageTask{}
	mi := &file_v1_openlineage_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenLineageTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenLineageTask) ProtoMessage() {}

func (x *OpenLineageTask) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenLineageTask.ProtoReflect.Descriptor instead.
func (*OpenLineageTask) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{2}
}

func (x *OpenLineageTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenLineageTask) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *OpenLineageTask) GetJobNamespace() string {
	if x != nil {
		return x.JobNamespace
	}
	return ""
}

func (x *OpenLineageTask) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *OpenLineageTask) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *OpenLineageTask) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *OpenLineageTask) GetProcessingType() string {
	if x != nil {
		return x.ProcessingType
	}
	return ""
}

func (x *OpenLineageTask) GetParentJobNamespace() string {
	if x != nil {
		return x.ParentJobNamespace
	}
	return ""
}

func (x *OpenLineageTask) GetParentJobName() string {
	if x != nil {
		return x.ParentJobName
	}
	return ""
}

func (x *OpenLineageTask) GetRootJobNamespace() string {
	if x != nil {
		return x.RootJobNamespace
	}
	return ""
}

func (x *OpenLineageTask) GetRootJobName() string {
	if x != nil {
		return x.RootJobName
	}
	return ""
}

func (x *OpenLineageTask) GetLatestRunGuid() string {
	if x != nil {
		return x.LatestRunGuid
	}
	return ""
}

func (x *OpenLineageTask) GetLatestRunId() string {
	if x != nil {
		return x.LatestRunId
	}
	return ""
}

func (x *OpenLineageTask) GetLatestEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestEventTime
	}
	return nil
}

func (x *OpenLineageTask) GetLatestProducer() string {
	if x != nil {
		return x.LatestProducer
	}
	return ""
}

func (x *OpenLineageTask) GetLatestSource() string {
	if x != nil {
		return x.LatestSource
	}
	return ""
}

func (x *OpenLineageTask) GetRunCount() int32 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *OpenLineageTask) GetLineageRunCount() int32 {
	if x != nil {
		return x.LineageRunCount
	}
	return 0
}

func (x *OpenLineageTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OpenLineageTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *OpenLineageTask) GetAirflowDagUrl() string {
	if x != nil {
		return x.AirflowDagUrl
	}
	return ""
}

func (x *OpenLineageTask) GetLatestEventType() string {
	if x != nil {
		return x.LatestEventType
	}
	return ""
}

type OpenLineageDatasetResource struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Guid                  string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Namespace             string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                  string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DatasetType           string                 `protobuf:"bytes,4,opt,name=dataset_type,json=datasetType,proto3" json:"dataset_type,omitempty"`
	ResolvedTarget        string                 `protobuf:"bytes,5,opt,name=resolved_target,json=resolvedTarget,proto3" json:"resolved_target,omitempty"`
	ResolvedMetaType      MetaType               `protobuf:"varint,6,opt,name=resolved_meta_type,json=resolvedMetaType,proto3,enum=metaxisdata.v1.MetaType" json:"resolved_meta_type,omitempty"`
	Internal              bool                   `protobuf:"varint,7,opt,name=internal,proto3" json:"internal,omitempty"`
	SupportsColumnLineage bool                   `protobuf:"varint,8,opt,name=supports_column_lineage,json=supportsColumnLineage,proto3" json:"supports_column_lineage,omitempty"`
	LastSeen              *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	SourceJobCount        int32                  `protobuf:"varint,10,opt,name=source_job_count,json=sourceJobCount,proto3" json:"source_job_count,omitempty"`
	TargetJobCount        int32                  `protobuf:"varint,11,opt,name=target_job_count,json=targetJobCount,proto3" json:"target_job_count,omitempty"`
	Integrations          []string               `protobuf:"bytes,12,rep,name=integrations,proto3" json:"integrations,omitempty"`
	Sources               []string               `protobuf:"bytes,13,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OpenLineageDatasetResource) Reset() {
	*x = OpenLineageDatasetResource{}
	mi := &file_v1_openlineage_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenLineageDatasetResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenLineageDatasetResource) ProtoMessage() {}

func (x *OpenLineageDatasetResource) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenLineageDatasetResource.ProtoReflect.Descriptor instead.
func (*OpenLineageDatasetResource) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{3}
}

func (x *OpenLineageDatasetResource) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *OpenLineageDatasetResource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *OpenLineageDatasetResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenLineageDatasetResource) GetDatasetType() string {
	if x != nil {
		return x.DatasetType
	}
	return ""
}

func (x *OpenLineageDatasetResource) GetResolvedTarget() string {
	if x != nil {
		return x.ResolvedTarget
	}
	return ""
}

func (x *OpenLineageDatasetResource) GetResolvedMetaType() MetaType {
	if x != nil {
		return x.ResolvedMetaType
	}
	return MetaType_UNSPECIFIED
}

func (x *OpenLineageDatasetResource) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

func (x *OpenLineageDatasetResource) GetSupportsColumnLineage() bool {
	if x != nil {
		return x.SupportsColumnLineage
	}
	return false
}

func (x *OpenLineageDatasetResource) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *OpenLineageDatasetResource) GetSourceJobCount() int32 {
	if x != nil {
		return x.SourceJobCount
	}
	return 0
}

func (x *OpenLineageDatasetResource) GetTargetJobCount() int32 {
	if x != nil {
		return x.TargetJobCount
	}
	return 0
}

func (x *OpenLineageDatasetResource) GetIntegrations() []string {
	if x != nil {
		return x.Integrations
	}
	return nil
}

func (x *OpenLineageDatasetResource) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type OpenLineageDatasetField struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ColumnLineageReady bool                   `protobuf:"varint,4,opt,name=column_lineage_ready,json=columnLineageReady,proto3" json:"column_lineage_ready,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OpenLineageDatasetField) Reset() {
	*x = OpenLineageDatasetField{}
	mi := &file_v1_openlineage_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenLineageDatasetField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenLineageDatasetField) ProtoMessage() {}

func (x *OpenLineageDatasetField) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenLineageDatasetField.ProtoReflect.Descriptor instead.
func (*OpenLineageDatasetField) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{4}
}

func (x *OpenLineageDatasetField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpenLineageDatasetField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OpenLineageDatasetField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OpenLineageDatasetField) GetColumnLineageReady() bool {
	if x != nil {
		return x.ColumnLineageReady
	}
	return false
}

type OpenLineageDatasetJobResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskGuid      string                 `protobuf:"bytes,1,opt,name=task_guid,json=taskGuid,proto3" json:"task_guid,omitempty"`
	JobNamespace  string                 `protobuf:"bytes,2,opt,name=job_namespace,json=jobNamespace,proto3" json:"job_namespace,omitempty"`
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType       string                 `protobuf:"bytes,4,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	Integration   string                 `protobuf:"bytes,5,opt,name=integration,proto3" json:"integration,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	RunCount      int32                  `protobuf:"varint,7,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	ReadsDataset  bool                   `protobuf:"varint,8,opt,name=reads_dataset,json=readsDataset,proto3" json:"reads_dataset,omitempty"`
	WritesDataset bool                   `protobuf:"varint,9,opt,name=writes_dataset,json=writesDataset,proto3" json:"writes_dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenLineageDatasetJobResource) Reset() {
	*x = OpenLineageDatasetJobResource{}
	mi := &file_v1_openlineage_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenLineageDatasetJobResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenLineageDatasetJobResource) ProtoMessage() {}

func (x *OpenLineageDatasetJobResource) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenLineageDatasetJobResource.ProtoReflect.Descriptor instead.
func (*OpenLineageDatasetJobResource) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{5}
}

func (x *OpenLineageDatasetJobResource) GetTaskGuid() string {
	if x != nil {
		return x.TaskGuid
	}
	return ""
}

func (x *OpenLineageDatasetJobResource) GetJobNamespace() string {
	if x != nil {
		return x.JobNamespace
	}
	return ""
}

func (x *OpenLineageDatasetJobResource) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *OpenLineageDatasetJobResource) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *OpenLineageDatasetJobResource) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *OpenLineageDatasetJobResource) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *OpenLineageDatasetJobResource) GetRunCount() int32 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *OpenLineageDatasetJobResource) GetReadsDataset() bool {
	if x != nil {
		return x.ReadsDataset
	}
	return false
}

func (x *OpenLineageDatasetJobResource) GetWritesDataset() bool {
	if x != nil {
		return x.WritesDataset
	}
	return false
}

type OpenLineageDatasetRunResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	TaskGuid      string                 `protobuf:"bytes,2,opt,name=task_guid,json=taskGuid,proto3" json:"task_guid,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	JobNamespace  string                 `protobuf:"bytes,4,opt,name=job_namespace,json=jobNamespace,proto3" json:"job_namespace,omitempty"`
	JobName       string                 `protobuf:"bytes,5,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType       string                 `protobuf:"bytes,6,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	EventType     string                 `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventTime     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	HasLineage    bool                   `protobuf:"varint,9,opt,name=has_lineage,json=hasLineage,proto3" json:"has_lineage,omitempty"`
	ReadsDataset  bool                   `protobuf:"varint,10,opt,name=reads_dataset,json=readsDataset,proto3" json:"reads_dataset,omitempty"`
	WritesDataset bool                   `protobuf:"varint,11,opt,name=writes_dataset,json=writesDataset,proto3" json:"writes_dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenLineageDatasetRunResource) Reset() {
	*x = OpenLineageDatasetRunResource{}
	mi := &file_v1_openlineage_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenLineageDatasetRunResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenLineageDatasetRunResource) ProtoMessage() {}

func (x *OpenLineageDatasetRunResource) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenLineageDatasetRunResource.ProtoReflect.Descriptor instead.
func (*OpenLineageDatasetRunResource) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{6}
}

func (x *OpenLineageDatasetRunResource) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *OpenLineageDatasetRunResource) GetTaskGuid() string {
	if x != nil {
		return x.TaskGuid
	}
	return ""
}

func (x *OpenLineageDatasetRunResource) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *OpenLineageDatasetRunResource) GetJobNamespace() string {
	if x != nil {
		return x.JobNamespace
	}
	return ""
}

func (x *OpenLineageDatasetRunResource) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *OpenLineageDatasetRunResource) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *OpenLineageDatasetRunResource) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OpenLineageDatasetRunResource) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *OpenLineageDatasetRunResource) GetHasLineage() bool {
	if x != nil {
		return x.HasLineage
	}
	return false
}

func (x *OpenLineageDatasetRunResource) GetReadsDataset() bool {
	if x != nil {
		return x.ReadsDataset
	}
	return false
}

func (x *OpenLineageDatasetRunResource) GetWritesDataset() bool {
	if x != nil {
		return x.WritesDataset
	}
	return false
}

type OpenLineageDatasetDetailResource struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Dataset       *OpenLineageDatasetResource      `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	SchemaFields  []*OpenLineageDatasetField       `protobuf:"bytes,2,rep,name=schema_fields,json=schemaFields,proto3" json:"schema_fields,omitempty"`
	RelatedJobs   []*OpenLineageDatasetJobResource `protobuf:"bytes,3,rep,name=related_jobs,json=relatedJobs,proto3" json:"related_jobs,omitempty"`
	RecentRuns    []*OpenLineageDatasetRunResource `protobuf:"bytes,4,rep,name=recent_runs,json=recentRuns,proto3" json:"recent_runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenLineageDatasetDetailResource) Reset() {
	*x = OpenLineageDatasetDetailResource{}
	mi := &file_v1_openlineage_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenLineageDatasetDetailResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenLineageDatasetDetailResource) ProtoMessage() {}

func (x *OpenLineageDatasetDetailResource) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenLineageDatasetDetailResource.ProtoReflect.Descriptor instead.
func (*OpenLineageDatasetDetailResource) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{7}
}

func (x *OpenLineageDatasetDetailResource) GetDataset() *OpenLineageDatasetResource {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *OpenLineageDatasetDetailResource) GetSchemaFields() []*OpenLineageDatasetField {
	if x != nil {
		return x.SchemaFields
	}
	return nil
}

func (x *OpenLineageDatasetDetailResource) GetRelatedJobs() []*OpenLineageDatasetJobResource {
	if x != nil {
		return x.RelatedJobs
	}
	return nil
}

func (x *OpenLineageDatasetDetailResource) GetRecentRuns() []*OpenLineageDatasetRunResource {
	if x != nil {
		return x.RecentRuns
	}
	return nil
}

type ListOpenLineageTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	JobNamespace  string                 `protobuf:"bytes,3,opt,name=job_namespace,json=jobNamespace,proto3" json:"job_namespace,omitempty"`
	JobName       string                 `protobuf:"bytes,4,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobType       string                 `protobuf:"bytes,5,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	LineageOnly   bool                   `protobuf:"varint,6,opt,name=lineage_only,json=lineageOnly,proto3" json:"lineage_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenLineageTasksRequest) Reset() {
	*x = ListOpenLineageTasksRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenLineageTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenLineageTasksRequest) ProtoMessage() {}

func (x *ListOpenLineageTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenLineageTasksRequest.ProtoReflect.Descriptor instead.
func (*ListOpenLineageTasksRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListOpenLineageTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOpenLineageTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOpenLineageTasksRequest) GetJobNamespace() string {
	if x != nil {
		return x.JobNamespace
	}
	return ""
}

func (x *ListOpenLineageTasksRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ListOpenLineageTasksRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ListOpenLineageTasksRequest) GetLineageOnly() bool {
	if x != nil {
		return x.LineageOnly
	}
	return false
}

type ListOpenLineageDatasetsRequest struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	PageSize          int32                   `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken         string                  `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Search            string                  `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Namespace         string                  `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Integration       string                  `protobuf:"bytes,5,opt,name=integration,proto3" json:"integration,omitempty"`
	Source            string                  `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	DatasetScope      OpenLineageDatasetScope `protobuf:"varint,7,opt,name=dataset_scope,json=datasetScope,proto3,enum=metaxisdata.v1.OpenLineageDatasetScope" json:"dataset_scope,omitempty"`
	ColumnLineageOnly bool                    `protobuf:"varint,8,opt,name=column_lineage_only,json=columnLineageOnly,proto3" json:"column_lineage_only,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListOpenLineageDatasetsRequest) Reset() {
	*x = ListOpenLineageDatasetsRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenLineageDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenLineageDatasetsRequest) ProtoMessage() {}

func (x *ListOpenLineageDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenLineageDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListOpenLineageDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListOpenLineageDatasetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOpenLineageDatasetsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOpenLineageDatasetsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListOpenLineageDatasetsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListOpenLineageDatasetsRequest) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *ListOpenLineageDatasetsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListOpenLineageDatasetsRequest) GetDatasetScope() OpenLineageDatasetScope {
	if x != nil {
		return x.DatasetScope
	}
	return OpenLineageDatasetScope_OPENLINEAGE_DATASET_SCOPE_UNSPECIFIED
}

func (x *ListOpenLineageDatasetsRequest) GetColumnLineageOnly() bool {
	if x != nil {
		return x.ColumnLineageOnly
	}
	return false
}

type GetOpenLineageDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenLineageDatasetRequest) Reset() {
	*x = GetOpenLineageDatasetRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenLineageDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenLineageDatasetRequest) ProtoMessage() {}

func (x *GetOpenLineageDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenLineageDatasetRequest.ProtoReflect.Descriptor instead.
func (*GetOpenLineageDatasetRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetOpenLineageDatasetRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type ListOpenLineageTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*OpenLineageTask     `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenLineageTasksResponse) Reset() {
	*x = ListOpenLineageTasksResponse{}
	mi := &file_v1_openlineage_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenLineageTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenLineageTasksResponse) ProtoMessage() {}

func (x *ListOpenLineageTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenLineageTasksResponse.ProtoReflect.Descriptor instead.
func (*ListOpenLineageTasksResponse) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListOpenLineageTasksResponse) GetTasks() []*OpenLineageTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListOpenLineageTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListOpenLineageDatasetsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Datasets      []*OpenLineageDatasetResource `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	NextPageToken string                        `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenLineageDatasetsResponse) Reset() {
	*x = ListOpenLineageDatasetsResponse{}
	mi := &file_v1_openlineage_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenLineageDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenLineageDatasetsResponse) ProtoMessage() {}

func (x *ListOpenLineageDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenLineageDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListOpenLineageDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListOpenLineageDatasetsResponse) GetDatasets() []*OpenLineageDatasetResource {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *ListOpenLineageDatasetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetOpenLineageTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the task to retrieve.
	// Format: openlineage/tasks/{task}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenLineageTaskRequest) Reset() {
	*x = GetOpenLineageTaskRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenLineageTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenLineageTaskRequest) ProtoMessage() {}

func (x *GetOpenLineageTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenLineageTaskRequest.ProtoReflect.Descriptor instead.
func (*GetOpenLineageTaskRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetOpenLineageTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListOpenLineageRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	JobNamespace  string                 `protobuf:"bytes,3,opt,name=job_namespace,json=jobNamespace,proto3" json:"job_namespace,omitempty"`
	JobName       string                 `protobuf:"bytes,4,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	TaskGuid      string                 `protobuf:"bytes,5,opt,name=task_guid,json=taskGuid,proto3" json:"task_guid,omitempty"`
	JobType       string                 `protobuf:"bytes,6,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	EventType     string                 `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	HasLineage    bool                   `protobuf:"varint,8,opt,name=has_lineage,json=hasLineage,proto3" json:"has_lineage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenLineageRunsRequest) Reset() {
	*x = ListOpenLineageRunsRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenLineageRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenLineageRunsRequest) ProtoMessage() {}

func (x *ListOpenLineageRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenLineageRunsRequest.ProtoReflect.Descriptor instead.
func (*ListOpenLineageRunsRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListOpenLineageRunsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOpenLineageRunsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOpenLineageRunsRequest) GetJobNamespace() string {
	if x != nil {
		return x.JobNamespace
	}
	return ""
}

func (x *ListOpenLineageRunsRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *ListOpenLineageRunsRequest) GetTaskGuid() string {
	if x != nil {
		return x.TaskGuid
	}
	return ""
}

func (x *ListOpenLineageRunsRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *ListOpenLineageRunsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ListOpenLineageRunsRequest) GetHasLineage() bool {
	if x != nil {
		return x.HasLineage
	}
	return false
}

type ListOpenLineageRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*OpenLineageRun      `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOpenLineageRunsResponse) Reset() {
	*x = ListOpenLineageRunsResponse{}
	mi := &file_v1_openlineage_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOpenLineageRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpenLineageRunsResponse) ProtoMessage() {}

func (x *ListOpenLineageRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpenLineageRunsResponse.ProtoReflect.Descriptor instead.
func (*ListOpenLineageRunsResponse) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListOpenLineageRunsResponse) GetRuns() []*OpenLineageRun {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *ListOpenLineageRunsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetOpenLineageRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the run to retrieve.
	// Format: openlineage/runs/{run}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenLineageRunRequest) Reset() {
	*x = GetOpenLineageRunRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenLineageRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenLineageRunRequest) ProtoMessage() {}

func (x *GetOpenLineageRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenLineageRunRequest.ProtoReflect.Descriptor instead.
func (*GetOpenLineageRunRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetOpenLineageRunRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateNamespaceMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mapping to create. The server assigns its resource ID.
	Mapping       *NamespaceMapping `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceMappingRequest) Reset() {
	*x = CreateNamespaceMappingRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceMappingRequest) ProtoMessage() {}

func (x *CreateNamespaceMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceMappingRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceMappingRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateNamespaceMappingRequest) GetMapping() *NamespaceMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

type ListNamespaceMappingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespaceMappingsRequest) Reset() {
	*x = ListNamespaceMappingsRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespaceMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespaceMappingsRequest) ProtoMessage() {}

func (x *ListNamespaceMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespaceMappingsRequest.ProtoReflect.Descriptor instead.
func (*ListNamespaceMappingsRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{18}
}

type ListNamespaceMappingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mappings      []*NamespaceMapping    `protobuf:"bytes,1,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespaceMappingsResponse) Reset() {
	*x = ListNamespaceMappingsResponse{}
	mi := &file_v1_openlineage_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespaceMappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespaceMappingsResponse) ProtoMessage() {}

func (x *ListNamespaceMappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespaceMappingsResponse.ProtoReflect.Descriptor instead.
func (*ListNamespaceMappingsResponse) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListNamespaceMappingsResponse) GetMappings() []*NamespaceMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type UpdateNamespaceMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mapping to update. Its `name` field identifies the row.
	Mapping *NamespaceMapping `protobuf:"bytes,1,opt,name=mapping,proto3" json:"mapping,omitempty"`
	// The list of fields to update. When omitted, the fields the request carries
	// are updated; `database_name` is always written so it can be cleared.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNamespaceMappingRequest) Reset() {
	*x = UpdateNamespaceMappingRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNamespaceMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNamespaceMappingRequest) ProtoMessage() {}

func (x *UpdateNamespaceMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNamespaceMappingRequest.ProtoReflect.Descriptor instead.
func (*UpdateNamespaceMappingRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateNamespaceMappingRequest) GetMapping() *NamespaceMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

func (x *UpdateNamespaceMappingRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteNamespaceMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the mapping to delete.
	// Format: openlineage/namespaceMappings/{namespace_mapping}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceMappingRequest) Reset() {
	*x = DeleteNamespaceMappingRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceMappingRequest) ProtoMessage() {}

func (x *DeleteNamespaceMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceMappingRequest.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceMappingRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteNamespaceMappingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type APIKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the API key.
	// Format: openlineage/apiKeys/{api_key}
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MaskedKey   string                 `protobuf:"bytes,2,opt,name=masked_key,json=maskedKey,proto3" json:"masked_key,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy   string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastUsedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	// Non-empty only when the key is revoked.
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKey) Reset() {
	*x = APIKey{}
	mi := &file_v1_openlineage_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKey) ProtoMessage() {}

func (x *APIKey) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKey.ProtoReflect.Descriptor instead.
func (*APIKey) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{22}
}

func (x *APIKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKey) GetMaskedKey() string {
	if x != nil {
		return x.MaskedKey
	}
	return ""
}

func (x *APIKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APIKey) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *APIKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *APIKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *APIKey) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{23}
}

func (x *CreateAPIKeyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateAPIKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plain-text API key. Only returned once at creation time.
	Key           string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ApiKey        *APIKey `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_v1_openlineage_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{24}
}

func (x *CreateAPIKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetApiKey() *APIKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{25}
}

type ListAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKeys       []*APIKey              `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysResponse) Reset() {
	*x = ListAPIKeysResponse{}
	mi := &file_v1_openlineage_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysResponse) ProtoMessage() {}

func (x *ListAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{26}
}

func (x *ListAPIKeysResponse) GetApiKeys() []*APIKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

type RevokeAPIKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the API key to revoke.
	// Format: openlineage/apiKeys/{api_key}
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAPIKeyRequest) Reset() {
	*x = RevokeAPIKeyRequest{}
	mi := &file_v1_openlineage_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAPIKeyRequest) ProtoMessage() {}

func (x *RevokeAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_openlineage_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1_openlineage_service_proto_rawDescGZIP(), []int{27}
}

func (x *RevokeAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_v1_openlineage_service_proto protoreflect.FileDescriptor

const file_v1_openlineage_service_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/openlineage_service.proto\x12\x0emetaxisdata.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13v1/annotation.proto\x1a\x19v1/database_service.proto\"\xf1\x02\n" +
	"\x10NamespaceMapping\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tB\x03\xe0A\x02R\tnamespace\x125\n" +
	"\x14instance_resource_id\x18\x03 \x01(\tB\x03\xe0A\x02R\x12instanceResourceId\x12#\n" +
	"\rdatabase_name\x18\x04 \x01(\tR\fdatabaseName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt:T\xeaAQ\n" +
	"\x1cmetaxisdata/NamespaceMapping\x121openlineage/namespaceMappings/{namespace_mapping}\"\x9c\b\n" +
	"\x0eOpenLineageRun\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\x12\x1b\n" +
	"\ttask_guid\x18\x03 \x01(\tR\btaskGuid\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12#\n" +
	"\rjob_namespace\x18\x05 \x01(\tR\fjobNamespace\x12\x19\n" +
	"\bjob_name\x18\x06 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\a \x01(\tR\ajobType\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\x129\n" +
	"\n" +
	"event_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12\x1a\n" +
	"\bproducer\x18\n" +
	" \x01(\tR\bproducer\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\x12 \n" +
	"\vintegration\x18\f \x01(\tR\vintegration\x12'\n" +
	"\x0fprocessing_type\x18\r \x01(\tR\x0eprocessingType\x120\n" +
	"\x14parent_job_namespace\x18\x0e \x01(\tR\x12parentJobNamespace\x12&\n" +
	"\x0fparent_job_name\x18\x0f \x01(\tR\rparentJobName\x12\"\n" +
	"\rparent_run_id\x18\x10 \x01(\tR\vparentRunId\x12,\n" +
	"\x12root_job_namespace\x18\x11 \x01(\tR\x10rootJobNamespace\x12\"\n" +
	"\rroot_job_name\x18\x12 \x01(\tR\vrootJobName\x12\x1e\n" +
	"\vroot_run_id\x18\x13 \x01(\tR\trootRunId\x12\x1f\n" +
	"\vinput_count\x18\x14 \x01(\x05R\n" +
	"inputCount\x12!\n" +
	"\foutput_count\x18\x15 \x01(\x05R\voutputCount\x12\x1f\n" +
	"\vhas_lineage\x18\x16 \x01(\bR\n" +
	"hasLineage\x129\n" +
	"\n" +
	"created_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1f\n" +
	"\vraw_payload\x18\x19 \x01(\tR\n" +
	"rawPayload\x12&\n" +
	"\x0fairflow_dag_url\x18\x1a \x01(\tR\rairflowDagUrl\x12-\n" +
	"\x13airflow_run_log_url\x18\x1b \x01(\tR\x10airflowRunLogUrl:7\xeaA4\n" +
	"\x1ametaxisdata/OpenLineageRun\x12\x16openlineage/runs/{run}\"\xbc\a\n" +
	"\x0fOpenLineageTask\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04guid\x18\x02 \x01(\tR\x04guid\x12#\n" +
	"\rjob_namespace\x18\x03 \x01(\tR\fjobNamespace\x12\x19\n" +
	"\bjob_name\x18\x04 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x05 \x01(\tR\ajobType\x12 \n" +
	"\vintegration\x18\x06 \x01(\tR\vintegration\x12'\n" +
	"\x0fprocessing_type\x18\a \x01(\tR\x0eprocessingType\x120\n" +
	"\x14parent_job_namespace\x18\b \x01(\tR\x12parentJobNamespace\x12&\n" +
	"\x0fparent_job_name\x18\t \x01(\tR\rparentJobName\x12,\n" +
	"\x12root_job_namespace\x18\n" +
	" \x01(\tR\x10rootJobNamespace\x12\"\n" +
	"\rroot_job_name\x18\v \x01(\tR\vrootJobName\x12&\n" +
	"\x0flatest_run_guid\x18\f \x01(\tR\rlatestRunGuid\x12\"\n" +
	"\rlatest_run_id\x18\r \x01(\tR\vlatestRunId\x12F\n" +
	"\x11latest_event_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x0flatestEventTime\x12'\n" +
	"\x0flatest_producer\x18\x0f \x01(\tR\x0elatestProducer\x12#\n" +
	"\rlatest_source\x18\x10 \x01(\tR\flatestSource\x12\x1b\n" +
	"\trun_count\x18\x11 \x01(\x05R\brunCount\x12*\n" +
	"\x11lineage_run_count\x18\x12 \x01(\x05R\x0flineageRunCount\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12&\n" +
	"\x0fairflow_dag_url\x18\x15 \x01(\tR\rairflowDagUrl\x12*\n" +
	"\x11latest_event_type\x18\x16 \x01(\tR\x0flatestEventType::\xeaA7\n" +
	"\x1bmetaxisdata/OpenLineageTask\x12\x18openlineage/tasks/{task}\"\x95\x04\n" +
	"\x1aOpenLineageDatasetResource\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fdataset_type\x18\x04 \x01(\tR\vdatasetType\x12'\n" +
	"\x0fresolved_target\x18\x05 \x01(\tR\x0eresolvedTarget\x12F\n" +
	"\x12resolved_meta_type\x18\x06 \x01(\x0e2\x18.metaxisdata.v1.MetaTypeR\x10resolvedMetaType\x12\x1a\n" +
	"\binternal\x18\a \x01(\bR\binternal\x126\n" +
	"\x17supports_column_lineage\x18\b \x01(\bR\x15supportsColumnLineage\x127\n" +
	"\tlast_seen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12(\n" +
	"\x10source_job_count\x18\n" +
	" \x01(\x05R\x0esourceJobCount\x12(\n" +
	"\x10target_job_count\x18\v \x01(\x05R\x0etargetJobCount\x12\"\n" +
	"\fintegrations\x18\f \x03(\tR\fintegrations\x12\x18\n" +
	"\asources\x18\r \x03(\tR\asources\"\x95\x01\n" +
	"\x17OpenLineageDatasetField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x14column_lineage_ready\x18\x04 \x01(\bR\x12columnLineageReady\"\xdb\x02\n" +
	"\x1dOpenLineageDatasetJobResource\x12\x1b\n" +
	"\ttask_guid\x18\x01 \x01(\tR\btaskGuid\x12#\n" +
	"\rjob_namespace\x18\x02 \x01(\tR\fjobNamespace\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x04 \x01(\tR\ajobType\x12 \n" +
	"\vintegration\x18\x05 \x01(\tR\vintegration\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1b\n" +
	"\trun_count\x18\a \x01(\x05R\brunCount\x12#\n" +
	"\rreads_dataset\x18\b \x01(\bR\freadsDataset\x12%\n" +
	"\x0ewrites_dataset\x18\t \x01(\bR\rwritesDataset\"\x89\x03\n" +
	"\x1dOpenLineageDatasetRunResource\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x1b\n" +
	"\ttask_guid\x18\x02 \x01(\tR\btaskGuid\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12#\n" +
	"\rjob_namespace\x18\x04 \x01(\tR\fjobNamespace\x12\x19\n" +
	"\bjob_name\x18\x05 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x06 \x01(\tR\ajobType\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\x129\n" +
	"\n" +
	"event_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12\x1f\n" +
	"\vhas_lineage\x18\t \x01(\bR\n" +
	"hasLineage\x12#\n" +
	"\rreads_dataset\x18\n" +
	" \x01(\bR\freadsDataset\x12%\n" +
	"\x0ewrites_dataset\x18\v \x01(\bR\rwritesDataset\"\xd8\x02\n" +
	" OpenLineageDatasetDetailResource\x12D\n" +
	"\adataset\x18\x01 \x01(\v2*.metaxisdata.v1.OpenLineageDatasetResourceR\adataset\x12L\n" +
	"\rschema_fields\x18\x02 \x03(\v2'.metaxisdata.v1.OpenLineageDatasetFieldR\fschemaFields\x12P\n" +
	"\frelated_jobs\x18\x03 \x03(\v2-.metaxisdata.v1.OpenLineageDatasetJobResourceR\vrelatedJobs\x12N\n" +
	"\vrecent_runs\x18\x04 \x03(\v2-.metaxisdata.v1.OpenLineageDatasetRunResourceR\n" +
	"recentRuns\"\xd7\x01\n" +
	"\x1bListOpenLineageTasksRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12#\n" +
	"\rjob_namespace\x18\x03 \x01(\tR\fjobNamespace\x12\x19\n" +
	"\bjob_name\x18\x04 \x01(\tR\ajobName\x12\x19\n" +
	"\bjob_type\x18\x05 \x01(\tR\ajobType\x12!\n" +
	"\flineage_only\x18\x06 \x01(\bR\vlineageOnly\"\xca\x02\n" +
	"\x1eListOpenLineageDatasetsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12 \n" +
	"\vintegration\x18\x05 \x01(\tR\vintegration\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12L\n" +
	"\rdataset_scope\x18\a \x01(\x0e2'.metaxisdata.v1.OpenLineageDatasetScopeR\fdatasetScope\x12.\n" +
	"\x13column_lineage_only\x18\b \x01(\bR\x11columnLineageOnly\"7\n" +
	"\x1cGetOpenLineageDatasetRequest\x12\x17\n" +
	"\x04guid\x18\x01 \x01(\tB\x03\xe0A\x02R\x04guid\"}\n" +
	"\x1cListOpenLineageTasksResponse\x125\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1f.metaxisdata.v1.OpenLineageTaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x91\x01\n" +
	"\x1fListOpenLineageDatasetsResponse\x12F\n" +
	"\bdatasets\x18\x01 \x03(\v2*.metaxisdata.v1.OpenLineageDatasetResourceR\bdatasets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"T\n" +
	"\x19GetOpenLineageTaskRequest\x127\n" +
	"\x04name\x18\x01 \x01(\tB#\xe0A\x02\xfaA\x1d\n" +
	"\x1bmetaxisdata/OpenLineageTaskR\x04name\"\x90\x02\n" +
	"\x1aListOpenLineageRunsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12#\n" +
	"\rjob_namespace\x18\x03 \x01(\tR\fjobNamespace\x12\x19\n" +
	"\bjob_name\x18\x04 \x01(\tR\ajobName\x12\x1b\n" +
	"\ttask_guid\x18\x05 \x01(\tR\btaskGuid\x12\x19\n" +
	"\bjob_type\x18\x06 \x01(\tR\ajobType\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\x12\x1f\n" +
	"\vhas_lineage\x18\b \x01(\bR\n" +
	"hasLineage\"y\n" +
	"\x1bListOpenLineageRunsResponse\x122\n" +
	"\x04runs\x18\x01 \x03(\v2\x1e.metaxisdata.v1.OpenLineageRunR\x04runs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"R\n" +
	"\x18GetOpenLineageRunRequest\x126\n" +
	"\x04name\x18\x01 \x01(\tB\"\xe0A\x02\xfaA\x1c\n" +
	"\x1ametaxisdata/OpenLineageRunR\x04name\"`\n" +
	"\x1dCreateNamespaceMappingRequest\x12?\n" +
	"\amapping\x18\x01 \x01(\v2 .metaxisdata.v1.NamespaceMappingB\x03\xe0A\x02R\amapping\"\x1e\n" +
	"\x1cListNamespaceMappingsRequest\"]\n" +
	"\x1dListNamespaceMappingsResponse\x12<\n" +
	"\bmappings\x18\x01 \x03(\v2 .metaxisdata.v1.NamespaceMappingR\bmappings\"\x9d\x01\n" +
	"\x1dUpdateNamespaceMappingRequest\x12?\n" +
	"\amapping\x18\x01 \x01(\v2 .metaxisdata.v1.NamespaceMappingB\x03\xe0A\x02R\amapping\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"Y\n" +
	"\x1dDeleteNamespaceMappingRequest\x128\n" +
	"\x04name\x18\x01 \x01(\tB$\xe0A\x02\xfaA\x1e\n" +
	"\x1cmetaxisdata/NamespaceMappingR\x04name\"\xe8\x02\n" +
	"\x06APIKey\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"masked_key\x18\x02 \x01(\tR\tmaskedKey\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"revoked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt:6\xeaA3\n" +
	"\x12metaxisdata/APIKey\x12\x1dopenlineage/apiKeys/{api_key}\"<\n" +
	"\x13CreateAPIKeyRequest\x12%\n" +
	"\vdescription\x18\x01 \x01(\tB\x03\xe0A\x02R\vdescription\"Y\n" +
	"\x14CreateAPIKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\aapi_key\x18\x02 \x01(\v2\x16.metaxisdata.v1.APIKeyR\x06apiKey\"\x14\n" +
	"\x12ListAPIKeysRequest\"H\n" +
	"\x13ListAPIKeysResponse\x121\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x16.metaxisdata.v1.APIKeyR\aapiKeys\"E\n" +
	"\x13RevokeAPIKeyRequest\x12.\n" +
	"\x04name\x18\x01 \x01(\tB\x1a\xe0A\x02\xfaA\x14\n" +
	"\x12metaxisdata/APIKeyR\x04name*\xb7\x01\n" +
	"\x17OpenLineageDatasetScope\x12)\n" +
	"%OPENLINEAGE_DATASET_SCOPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dOPENLINEAGE_DATASET_SCOPE_ALL\x10\x01\x12&\n" +
	"\"OPENLINEAGE_DATASET_SCOPE_INTERNAL\x10\x02\x12&\n" +
	"\"OPENLINEAGE_DATASET_SCOPE_EXTERNAL\x10\x032\x9b\x13\n" +
	"\x12OpenLineageService\x12\xb0\x01\n" +
	"\x14ListOpenLineageTasks\x12+.metaxisdata.v1.ListOpenLineageTasksRequest\x1a,.metaxisdata.v1.ListOpenLineageTasksResponse\"=\x8a\xea0\x1cmetaxisdata.openlineage.read\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/openlineage/tasks\x12\xbc\x01\n" +
	"\x17ListOpenLineageDatasets\x12..metaxisdata.v1.ListOpenLineageDatasetsRequest\x1a/.metaxisdata.v1.ListOpenLineageDatasetsResponse\"@\x8a\xea0\x1cmetaxisdata.openlineage.read\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/openlineage/datasets\x12\xb8\x01\n" +
	"\x15GetOpenLineageDataset\x12,.metaxisdata.v1.GetOpenLineageDatasetRequest\x1a0.metaxisdata.v1.OpenLineageDatasetDetailResource\"?\x8a\xea0\x1cmetaxisdata.openlineage.read\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/openlineage/dataset\x12\xa8\x01\n" +
	"\x12GetOpenLineageTask\x12).metaxisdata.v1.GetOpenLineageTaskRequest\x1a\x1f.metaxisdata.v1.OpenLineageTask\"F\x8a\xea0\x1cmetaxisdata.openlineage.read\x82\xd3\xe4\x93\x02 \x12\x1e/v1/{name=openlineage/tasks/*}\x12\xac\x01\n" +
	"\x13ListOpenLineageRuns\x12*.metaxisdata.v1.ListOpenLineageRunsRequest\x1a+.metaxisdata.v1.ListOpenLineageRunsResponse\"<\x8a\xea0\x1cmetaxisdata.openlineage.read\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/openlineage/runs\x12\xa4\x01\n" +
	"\x11GetOpenLineageRun\x12(.metaxisdata.v1.GetOpenLineageRunRequest\x1a\x1e.metaxisdata.v1.OpenLineageRun\"E\x8a\xea0\x1cmetaxisdata.openlineage.read\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/{name=openlineage/runs/*}\x12\xd5\x01\n" +
	"\x16CreateNamespaceMapping\x12-.metaxisdata.v1.CreateNamespaceMappingRequest\x1a .metaxisdata.v1.NamespaceMapping\"j\x8a\xea00metaxisdata.openlineage.namespaceMappings.create\x98\xea0\x01\x82\xd3\xe4\x93\x02,:\amapping\"!/v1/openlineage/namespaceMappings\x12\xd1\x01\n" +
	"\x15ListNamespaceMappings\x12,.metaxisdata.v1.ListNamespaceMappingsRequest\x1a-.metaxisdata.v1.ListNamespaceMappingsResponse\"[\x8a\xea0.metaxisdata.openlineage.namespaceMappings.list\x82\xd3\xe4\x93\x02#\x12!/v1/openlineage/namespaceMappings\x12\xe6\x01\n" +
	"\x16UpdateNamespaceMapping\x12-.metaxisdata.v1.UpdateNamespaceMappingRequest\x1a .metaxisdata.v1.NamespaceMapping\"{\x8a\xea00metaxisdata.openlineage.namespaceMappings.update\x98\xea0\x01\x82\xd3\xe4\x93\x02=:\amapping22/v1/{mapping.name=openlineage/namespaceMappings/*}\x12\xcb\x01\n" +
	"\x16DeleteNamespaceMapping\x12-.metaxisdata.v1.DeleteNamespaceMappingRequest\x1a\x16.google.protobuf.Empty\"j\x8a\xea00metaxisdata.openlineage.namespaceMappings.delete\x98\xea0\x01\x82\xd3\xe4\x93\x02,**/v1/{name=openlineage/namespaceMappings/*}\x12\xab\x01\n" +
	"\fCreateAPIKey\x12#.metaxisdata.v1.CreateAPIKeyRequest\x1a$.metaxisdata.v1.CreateAPIKeyResponse\"P\x8a\xea0&metaxisdata.openlineage.apiKeys.create\x98\xea0\x01\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/openlineage/apiKeys\x12\x9f\x01\n" +
	"\vListAPIKeys\x12\".metaxisdata.v1.ListAPIKeysRequest\x1a#.metaxisdata.v1.ListAPIKeysResponse\"G\x8a\xea0$metaxisdata.openlineage.apiKeys.list\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/openlineage/apiKeys\x12\xa3\x01\n" +
	"\fRevokeAPIKey\x12#.metaxisdata.v1.RevokeAPIKeyRequest\x1a\x16.google.protobuf.Empty\"V\x8a\xea0&metaxisdata.openlineage.apiKeys.delete\x98\xea0\x01\x82\xd3\xe4\x93\x02\"* /v1/{name=openlineage/apiKeys/*}B6Z4github.com/Ranxy/metaxisdata/backend/generated-go/v1b\x06proto3"

var (
	file_v1_openlineage_service_proto_rawDescOnce sync.Once
	file_v1_openlineage_service_proto_rawDescData []byte
)

func file_v1_openlineage_service_proto_rawDescGZIP() []byte {
	file_v1_openlineage_service_proto_rawDescOnce.Do(func() {
		file_v1_openlineage_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_openlineage_service_proto_rawDesc), len(file_v1_openlineage_service_proto_rawDesc)))
	})
	return file_v1_openlineage_service_proto_rawDescData
}

var file_v1_openlineage_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_openlineage_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_v1_openlineage_service_proto_goTypes = []any{
	(OpenLineageDatasetScope)(0),             // 0: metaxisdata.v1.OpenLineageDatasetScope
	(*NamespaceMapping)(nil),                 // 1: metaxisdata.v1.NamespaceMapping
	(*OpenLineageRun)(nil),                   // 2: metaxisdata.v1.OpenLineageRun
	(*OpenLineageTask)(nil),                  // 3: metaxisdata.v1.OpenLineageTask
	(*OpenLineageDatasetResource)(nil),       // 4: metaxisdata.v1.OpenLineageDatasetResource
	(*OpenLineageDatasetField)(nil),          // 5: metaxisdata.v1.OpenLineageDatasetField
	(*OpenLineageDatasetJobResource)(nil),    // 6: metaxisdata.v1.OpenLineageDatasetJobResource
	(*OpenLineageDatasetRunResource)(nil),    // 7: metaxisdata.v1.OpenLineageDatasetRunResource
	(*OpenLineageDatasetDetailResource)(nil), // 8: metaxisdata.v1.OpenLineageDatasetDetailResource
	(*ListOpenLineageTasksRequest)(nil),      // 9: metaxisdata.v1.ListOpenLineageTasksRequest
	(*ListOpenLineageDatasetsRequest)(nil),   // 10: metaxisdata.v1.ListOpenLineageDatasetsRequest
	(*GetOpenLineageDatasetRequest)(nil),     // 11: metaxisdata.v1.GetOpenLineageDatasetRequest
	(*ListOpenLineageTasksResponse)(nil),     // 12: metaxisdata.v1.ListOpenLineageTasksResponse
	(*ListOpenLineageDatasetsResponse)(nil),  // 13: metaxisdata.v1.ListOpenLineageDatasetsResponse
	(*GetOpenLineageTaskRequest)(nil),        // 14: metaxisdata.v1.GetOpenLineageTaskRequest
	(*ListOpenLineageRunsRequest)(nil),       // 15: metaxisdata.v1.ListOpenLineageRunsRequest
	(*ListOpenLineageRunsResponse)(nil),      // 16: metaxisdata.v1.ListOpenLineageRunsResponse
	(*GetOpenLineageRunRequest)(nil),         // 17: metaxisdata.v1.GetOpenLineageRunRequest
	(*CreateNamespaceMappingRequest)(nil),    // 18: metaxisdata.v1.CreateNamespaceMappingRequest
	(*ListNamespaceMappingsRequest)(nil),     // 19: metaxisdata.v1.ListNamespaceMappingsRequest
	(*ListNamespaceMappingsResponse)(nil),    // 20: metaxisdata.v1.ListNamespaceMappingsResponse
	(*UpdateNamespaceMappingRequest)(nil),    // 21: metaxisdata.v1.UpdateNamespaceMappingRequest
	(*DeleteNamespaceMappingRequest)(nil),    // 22: metaxisdata.v1.DeleteNamespaceMappingRequest
	(*APIKey)(nil),                           // 23: metaxisdata.v1.APIKey
	(*CreateAPIKeyRequest)(nil),              // 24: metaxisdata.v1.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil),             // 25: metaxisdata.v1.CreateAPIKeyResponse
	(*ListAPIKeysRequest)(nil),               // 26: metaxisdata.v1.ListAPIKeysRequest
	(*ListAPIKeysResponse)(nil),              // 27: metaxisdata.v1.ListAPIKeysResponse
	(*RevokeAPIKeyRequest)(nil),              // 28: metaxisdata.v1.RevokeAPIKeyRequest
	(*timestamppb.Timestamp)(nil),            // 29: google.protobuf.Timestamp
	(MetaType)(0),                            // 30: metaxisdata.v1.MetaType
	(*fieldmaskpb.FieldMask)(nil),            // 31: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                    // 32: google.protobuf.Empty
}
var file_v1_openlineage_service_proto_depIdxs = []int32{
	29, // 0: metaxisdata.v1.NamespaceMapping.created_at:type_name -> google.protobuf.Timestamp
	29, // 1: metaxisdata.v1.NamespaceMapping.updated_at:type_name -> google.protobuf.Timestamp
	29, // 2: metaxisdata.v1.OpenLineageRun.event_time:type_name -> google.protobuf.Timestamp
	29, // 3: metaxisdata.v1.OpenLineageRun.created_at:type_name -> google.protobuf.Timestamp
	29, // 4: metaxisdata.v1.OpenLineageRun.updated_at:type_name -> google.protobuf.Timestamp
	29, // 5: metaxisdata.v1.OpenLineageTask.latest_event_time:type_name -> google.protobuf.Timestamp
	29, // 6: metaxisdata.v1.OpenLineageTask.created_at:type_name -> google.protobuf.Timestamp
	29, // 7: metaxisdata.v1.OpenLineageTask.updated_at:type_name -> google.protobuf.Timestamp
	30, // 8: metaxisdata.v1.OpenLineageDatasetResource.resolved_meta_type:type_name -> metaxisdata.v1.MetaType
	29, // 9: metaxisdata.v1.OpenLineageDatasetResource.last_seen:type_name -> google.protobuf.Timestamp
	29, // 10: metaxisdata.v1.OpenLineageDatasetJobResource.last_seen:type_name -> google.protobuf.Timestamp
	29, // 11: metaxisdata.v1.OpenLineageDatasetRunResource.event_time:type_name -> google.protobuf.Timestamp
	4,  // 12: metaxisdata.v1.OpenLineageDatasetDetailResource.dataset:type_name -> metaxisdata.v1.OpenLineageDatasetResource
	5,  // 13: metaxisdata.v1.OpenLineageDatasetDetailResource.schema_fields:type_name -> metaxisdata.v1.OpenLineageDatasetField
	6,  // 14: metaxisdata.v1.OpenLineageDatasetDetailResource.related_jobs:type_name -> metaxisdata.v1.OpenLineageDatasetJobResource
	7,  // 15: metaxisdata.v1.OpenLineageDatasetDetailResource.recent_runs:type_name -> metaxisdata.v1.OpenLineageDatasetRunResource
	0,  // 16: metaxisdata.v1.ListOpenLineageDatasetsRequest.dataset_scope:type_name -> metaxisdata.v1.OpenLineageDatasetScope
	3,  // 17: metaxisdata.v1.ListOpenLineageTasksResponse.tasks:type_name -> metaxisdata.v1.OpenLineageTask
	4,  // 18: metaxisdata.v1.ListOpenLineageDatasetsResponse.datasets:type_name -> metaxisdata.v1.OpenLineageDatasetResource
	2,  // 19: metaxisdata.v1.ListOpenLineageRunsResponse.runs:type_name -> metaxisdata.v1.OpenLineageRun
	1,  // 20: metaxisdata.v1.CreateNamespaceMappingRequest.mapping:type_name -> metaxisdata.v1.NamespaceMapping
	1,  // 21: metaxisdata.v1.ListNamespaceMappingsResponse.mappings:type_name -> metaxisdata.v1.NamespaceMapping
	1,  // 22: metaxisdata.v1.UpdateNamespaceMappingRequest.mapping:type_name -> metaxisdata.v1.NamespaceMapping
	31, // 23: metaxisdata.v1.UpdateNamespaceMappingRequest.update_mask:type_name -> google.protobuf.FieldMask
	29, // 24: metaxisdata.v1.APIKey.created_at:type_name -> google.protobuf.Timestamp
	29, // 25: metaxisdata.v1.APIKey.last_used_at:type_name -> google.protobuf.Timestamp
	29, // 26: metaxisdata.v1.APIKey.revoked_at:type_name -> google.protobuf.Timestamp
	23, // 27: metaxisdata.v1.CreateAPIKeyResponse.api_key:type_name -> metaxisdata.v1.APIKey
	23, // 28: metaxisdata.v1.ListAPIKeysResponse.api_keys:type_name -> metaxisdata.v1.APIKey
	9,  // 29: metaxisdata.v1.OpenLineageService.ListOpenLineageTasks:input_type -> metaxisdata.v1.ListOpenLineageTasksRequest
	10, // 30: metaxisdata.v1.OpenLineageService.ListOpenLineageDatasets:input_type -> metaxisdata.v1.ListOpenLineageDatasetsRequest
	11, // 31: metaxisdata.v1.OpenLineageService.GetOpenLineageDataset:input_type -> metaxisdata.v1.GetOpenLineageDatasetRequest
	14, // 32: metaxisdata.v1.OpenLineageService.GetOpenLineageTask:input_type -> metaxisdata.v1.GetOpenLineageTaskRequest
	15, // 33: metaxisdata.v1.OpenLineageService.ListOpenLineageRuns:input_type -> metaxisdata.v1.ListOpenLineageRunsRequest
	17, // 34: metaxisdata.v1.OpenLineageService.GetOpenLineageRun:input_type -> metaxisdata.v1.GetOpenLineageRunRequest
	18, // 35: metaxisdata.v1.OpenLineageService.CreateNamespaceMapping:input_type -> metaxisdata.v1.CreateNamespaceMappingRequest
	19, // 36: metaxisdata.v1.OpenLineageService.ListNamespaceMappings:input_type -> metaxisdata.v1.ListNamespaceMappingsRequest
	21, // 37: metaxisdata.v1.OpenLineageService.UpdateNamespaceMapping:input_type -> metaxisdata.v1.UpdateNamespaceMappingRequest
	22, // 38: metaxisdata.v1.OpenLineageService.DeleteNamespaceMapping:input_type -> metaxisdata.v1.DeleteNamespaceMappingRequest
	24, // 39: metaxisdata.v1.OpenLineageService.CreateAPIKey:input_type -> metaxisdata.v1.CreateAPIKeyRequest
	26, // 40: metaxisdata.v1.OpenLineageService.ListAPIKeys:input_type -> metaxisdata.v1.ListAPIKeysRequest
	28, // 41: metaxisdata.v1.OpenLineageService.RevokeAPIKey:input_type -> metaxisdata.v1.RevokeAPIKeyRequest
	12, // 42: metaxisdata.v1.OpenLineageService.ListOpenLineageTasks:output_type -> metaxisdata.v1.ListOpenLineageTasksResponse
	13, // 43: metaxisdata.v1.OpenLineageService.ListOpenLineageDatasets:output_type -> metaxisdata.v1.ListOpenLineageDatasetsResponse
	8,  // 44: metaxisdata.v1.OpenLineageService.GetOpenLineageDataset:output_type -> metaxisdata.v1.OpenLineageDatasetDetailResource
	3,  // 45: metaxisdata.v1.OpenLineageService.GetOpenLineageTask:output_type -> metaxisdata.v1.OpenLineageTask
	16, // 46: metaxisdata.v1.OpenLineageService.ListOpenLineageRuns:output_type -> metaxisdata.v1.ListOpenLineageRunsResponse
	2,  // 47: metaxisdata.v1.OpenLineageService.GetOpenLineageRun:output_type -> metaxisdata.v1.OpenLineageRun
	1,  // 48: metaxisdata.v1.OpenLineageService.CreateNamespaceMapping:output_type -> metaxisdata.v1.NamespaceMapping
	20, // 49: metaxisdata.v1.OpenLineageService.ListNamespaceMappings:output_type -> metaxisdata.v1.ListNamespaceMappingsResponse
	1,  // 50: metaxisdata.v1.OpenLineageService.UpdateNamespaceMapping:output_type -> metaxisdata.v1.NamespaceMapping
	32, // 51: metaxisdata.v1.OpenLineageService.DeleteNamespaceMapping:output_type -> google.protobuf.Empty
	25, // 52: metaxisdata.v1.OpenLineageService.CreateAPIKey:output_type -> metaxisdata.v1.CreateAPIKeyResponse
	27, // 53: metaxisdata.v1.OpenLineageService.ListAPIKeys:output_type -> metaxisdata.v1.ListAPIKeysResponse
	32, // 54: metaxisdata.v1.OpenLineageService.RevokeAPIKey:output_type -> google.protobuf.Empty
	42, // [42:55] is the sub-list for method output_type
	29, // [29:42] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_v1_openlineage_service_proto_init() }
func file_v1_openlineage_service_proto_init() {
	if File_v1_openlineage_service_proto != nil {
		return
	}
	file_v1_annotation_proto_init()
	file_v1_database_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_openlineage_service_proto_rawDesc), len(file_v1_openlineage_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_openlineage_service_proto_goTypes,
		DependencyIndexes: file_v1_openlineage_service_proto_depIdxs,
		EnumInfos:         file_v1_openlineage_service_proto_enumTypes,
		MessageInfos:      file_v1_openlineage_service_proto_msgTypes,
	}.Build()
	File_v1_openlineage_service_proto = out.File
	file_v1_openlineage_service_proto_goTypes = nil
	file_v1_openlineage_service_proto_depIdxs = nil
}
