// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/openlineage_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenLineageService_ListOpenLineageTasks_FullMethodName    = "/metaxisdata.v1.OpenLineageService/ListOpenLineageTasks"
	OpenLineageService_ListOpenLineageDatasets_FullMethodName = "/metaxisdata.v1.OpenLineageService/ListOpenLineageDatasets"
	OpenLineageService_GetOpenLineageDataset_FullMethodName   = "/metaxisdata.v1.OpenLineageService/GetOpenLineageDataset"
	OpenLineageService_GetOpenLineageTask_FullMethodName      = "/metaxisdata.v1.OpenLineageService/GetOpenLineageTask"
	OpenLineageService_ListOpenLineageRuns_FullMethodName     = "/metaxisdata.v1.OpenLineageService/ListOpenLineageRuns"
	OpenLineageService_GetOpenLineageRun_FullMethodName       = "/metaxisdata.v1.OpenLineageService/GetOpenLineageRun"
	OpenLineageService_CreateNamespaceMapping_FullMethodName  = "/metaxisdata.v1.OpenLineageService/CreateNamespaceMapping"
	OpenLineageService_ListNamespaceMapping_FullMethodName    = "/metaxisdata.v1.OpenLineageService/ListNamespaceMapping"
	OpenLineageService_UpdateNamespaceMapping_FullMethodName  = "/metaxisdata.v1.OpenLineageService/UpdateNamespaceMapping"
	OpenLineageService_DeleteNamespaceMapping_FullMethodName  = "/metaxisdata.v1.OpenLineageService/DeleteNamespaceMapping"
	OpenLineageService_CreateAPIKey_FullMethodName            = "/metaxisdata.v1.OpenLineageService/CreateAPIKey"
	OpenLineageService_ListAPIKey_FullMethodName              = "/metaxisdata.v1.OpenLineageService/ListAPIKey"
	OpenLineageService_RevokeAPIKey_FullMethodName            = "/metaxisdata.v1.OpenLineageService/RevokeAPIKey"
)

// OpenLineageServiceClient is the client API for OpenLineageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenLineageServiceClient interface {
	ListOpenLineageTasks(ctx context.Context, in *ListOpenLineageTasksRequest, opts ...grpc.CallOption) (*ListOpenLineageTasksResponse, error)
	ListOpenLineageDatasets(ctx context.Context, in *ListOpenLineageDatasetsRequest, opts ...grpc.CallOption) (*ListOpenLineageDatasetsResponse, error)
	GetOpenLineageDataset(ctx context.Context, in *GetOpenLineageDatasetRequest, opts ...grpc.CallOption) (*OpenLineageDatasetDetailResource, error)
	GetOpenLineageTask(ctx context.Context, in *GetOpenLineageTaskRequest, opts ...grpc.CallOption) (*OpenLineageTaskResource, error)
	ListOpenLineageRuns(ctx context.Context, in *ListOpenLineageRunsRequest, opts ...grpc.CallOption) (*ListOpenLineageRunsResponse, error)
	GetOpenLineageRun(ctx context.Context, in *GetOpenLineageRunRequest, opts ...grpc.CallOption) (*OpenLineageRunResource, error)
	CreateNamespaceMapping(ctx context.Context, in *CreateNamespaceMappingRequest, opts ...grpc.CallOption) (*NamespaceMappingResource, error)
	ListNamespaceMapping(ctx context.Context, in *ListNamespaceMappingRequest, opts ...grpc.CallOption) (*ListNamespaceMappingResponse, error)
	UpdateNamespaceMapping(ctx context.Context, in *UpdateNamespaceMappingRequest, opts ...grpc.CallOption) (*NamespaceMappingResource, error)
	DeleteNamespaceMapping(ctx context.Context, in *DeleteNamespaceMappingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error)
	ListAPIKey(ctx context.Context, in *ListAPIKeyRequest, opts ...grpc.CallOption) (*ListAPIKeyResponse, error)
	RevokeAPIKey(ctx context.Context, in *RevokeAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type openLineageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenLineageServiceClient(cc grpc.ClientConnInterface) OpenLineageServiceClient {
	return &openLineageServiceClient{cc}
}

func (c *openLineageServiceClient) ListOpenLineageTasks(ctx context.Context, in *ListOpenLineageTasksRequest, opts ...grpc.CallOption) (*ListOpenLineageTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOpenLineageTasksResponse)
	err := c.cc.Invoke(ctx, OpenLineageService_ListOpenLineageTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) ListOpenLineageDatasets(ctx context.Context, in *ListOpenLineageDatasetsRequest, opts ...grpc.CallOption) (*ListOpenLineageDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOpenLineageDatasetsResponse)
	err := c.cc.Invoke(ctx, OpenLineageService_ListOpenLineageDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) GetOpenLineageDataset(ctx context.Context, in *GetOpenLineageDatasetRequest, opts ...grpc.CallOption) (*OpenLineageDatasetDetailResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenLineageDatasetDetailResource)
	err := c.cc.Invoke(ctx, OpenLineageService_GetOpenLineageDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) GetOpenLineageTask(ctx context.Context, in *GetOpenLineageTaskRequest, opts ...grpc.CallOption) (*OpenLineageTaskResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenLineageTaskResource)
	err := c.cc.Invoke(ctx, OpenLineageService_GetOpenLineageTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) ListOpenLineageRuns(ctx context.Context, in *ListOpenLineageRunsRequest, opts ...grpc.CallOption) (*ListOpenLineageRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOpenLineageRunsResponse)
	err := c.cc.Invoke(ctx, OpenLineageService_ListOpenLineageRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) GetOpenLineageRun(ctx context.Context, in *GetOpenLineageRunRequest, opts ...grpc.CallOption) (*OpenLineageRunResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenLineageRunResource)
	err := c.cc.Invoke(ctx, OpenLineageService_GetOpenLineageRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) CreateNamespaceMapping(ctx context.Context, in *CreateNamespaceMappingRequest, opts ...grpc.CallOption) (*NamespaceMappingResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceMappingResource)
	err := c.cc.Invoke(ctx, OpenLineageService_CreateNamespaceMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) ListNamespaceMapping(ctx context.Context, in *ListNamespaceMappingRequest, opts ...grpc.CallOption) (*ListNamespaceMappingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespaceMappingResponse)
	err := c.cc.Invoke(ctx, OpenLineageService_ListNamespaceMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) UpdateNamespaceMapping(ctx context.Context, in *UpdateNamespaceMappingRequest, opts ...grpc.CallOption) (*NamespaceMappingResource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceMappingResource)
	err := c.cc.Invoke(ctx, OpenLineageService_UpdateNamespaceMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) DeleteNamespaceMapping(ctx context.Context, in *DeleteNamespaceMappingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OpenLineageService_DeleteNamespaceMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIKeyResponse)
	err := c.cc.Invoke(ctx, OpenLineageService_CreateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) ListAPIKey(ctx context.Context, in *ListAPIKeyRequest, opts ...grpc.CallOption) (*ListAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIKeyResponse)
	err := c.cc.Invoke(ctx, OpenLineageService_ListAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openLineageServiceClient) RevokeAPIKey(ctx context.Context, in *RevokeAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OpenLineageService_RevokeAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenLineageServiceServer is the server API for OpenLineageService service.
// All implementations must embed UnimplementedOpenLineageServiceServer
// for forward compatibility.
type OpenLineageServiceServer interface {
	ListOpenLineageTasks(context.Context, *ListOpenLineageTasksRequest) (*ListOpenLineageTasksResponse, error)
	ListOpenLineageDatasets(context.Context, *ListOpenLineageDatasetsRequest) (*ListOpenLineageDatasetsResponse, error)
	GetOpenLineageDataset(context.Context, *GetOpenLineageDatasetRequest) (*OpenLineageDatasetDetailResource, error)
	GetOpenLineageTask(context.Context, *GetOpenLineageTaskRequest) (*OpenLineageTaskResource, error)
	ListOpenLineageRuns(context.Context, *ListOpenLineageRunsRequest) (*ListOpenLineageRunsResponse, error)
	GetOpenLineageRun(context.Context, *GetOpenLineageRunRequest) (*OpenLineageRunResource, error)
	CreateNamespaceMapping(context.Context, *CreateNamespaceMappingRequest) (*NamespaceMappingResource, error)
	ListNamespaceMapping(context.Context, *ListNamespaceMappingRequest) (*ListNamespaceMappingResponse, error)
	UpdateNamespaceMapping(context.Context, *UpdateNamespaceMappingRequest) (*NamespaceMappingResource, error)
	DeleteNamespaceMapping(context.Context, *DeleteNamespaceMappingRequest) (*emptypb.Empty, error)
	CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error)
	ListAPIKey(context.Context, *ListAPIKeyRequest) (*ListAPIKeyResponse, error)
	RevokeAPIKey(context.Context, *RevokeAPIKeyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedOpenLineageServiceServer()
}

// UnimplementedOpenLineageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenLineageServiceServer struct{}

func (UnimplementedOpenLineageServiceServer) ListOpenLineageTasks(context.Context, *ListOpenLineageTasksRequest) (*ListOpenLineageTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOpenLineageTasks not implemented")
}
func (UnimplementedOpenLineageServiceServer) ListOpenLineageDatasets(context.Context, *ListOpenLineageDatasetsRequest) (*ListOpenLineageDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOpenLineageDatasets not implemented")
}
func (UnimplementedOpenLineageServiceServer) GetOpenLineageDataset(context.Context, *GetOpenLineageDatasetRequest) (*OpenLineageDatasetDetailResource, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenLineageDataset not implemented")
}
func (UnimplementedOpenLineageServiceServer) GetOpenLineageTask(context.Context, *GetOpenLineageTaskRequest) (*OpenLineageTaskResource, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenLineageTask not implemented")
}
func (UnimplementedOpenLineageServiceServer) ListOpenLineageRuns(context.Context, *ListOpenLineageRunsRequest) (*ListOpenLineageRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOpenLineageRuns not implemented")
}
func (UnimplementedOpenLineageServiceServer) GetOpenLineageRun(context.Context, *GetOpenLineageRunRequest) (*OpenLineageRunResource, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenLineageRun not implemented")
}
func (UnimplementedOpenLineageServiceServer) CreateNamespaceMapping(context.Context, *CreateNamespaceMappingRequest) (*NamespaceMappingResource, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNamespaceMapping not implemented")
}
func (UnimplementedOpenLineageServiceServer) ListNamespaceMapping(context.Context, *ListNamespaceMappingRequest) (*ListNamespaceMappingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNamespaceMapping not implemented")
}
func (UnimplementedOpenLineageServiceServer) UpdateNamespaceMapping(context.Context, *UpdateNamespaceMappingRequest) (*NamespaceMappingResource, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNamespaceMapping not implemented")
}
func (UnimplementedOpenLineageServiceServer) DeleteNamespaceMapping(context.Context, *DeleteNamespaceMappingRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNamespaceMapping not implemented")
}
func (UnimplementedOpenLineageServiceServer) CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAPIKey not implemented")
}
func (UnimplementedOpenLineageServiceServer) ListAPIKey(context.Context, *ListAPIKeyRequest) (*ListAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAPIKey not implemented")
}
func (UnimplementedOpenLineageServiceServer) RevokeAPIKey(context.Context, *RevokeAPIKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAPIKey not implemented")
}
func (UnimplementedOpenLineageServiceServer) mustEmbedUnimplementedOpenLineageServiceServer() {}
func (UnimplementedOpenLineageServiceServer) testEmbeddedByValue()                            {}

// UnsafeOpenLineageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenLineageServiceServer will
// result in compilation errors.
type UnsafeOpenLineageServiceServer interface {
	mustEmbedUnimplementedOpenLineageServiceServer()
}

func RegisterOpenLineageServiceServer(s grpc.ServiceRegistrar, srv OpenLineageServiceServer) {
	// If the following call panics, it indicates UnimplementedOpenLineageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenLineageService_ServiceDesc, srv)
}

func _OpenLineageService_ListOpenLineageTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenLineageTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).ListOpenLineageTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_ListOpenLineageTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).ListOpenLineageTasks(ctx, req.(*ListOpenLineageTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_ListOpenLineageDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenLineageDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).ListOpenLineageDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_ListOpenLineageDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).ListOpenLineageDatasets(ctx, req.(*ListOpenLineageDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_GetOpenLineageDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenLineageDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).GetOpenLineageDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_GetOpenLineageDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).GetOpenLineageDataset(ctx, req.(*GetOpenLineageDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_GetOpenLineageTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenLineageTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).GetOpenLineageTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_GetOpenLineageTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).GetOpenLineageTask(ctx, req.(*GetOpenLineageTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_ListOpenLineageRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenLineageRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).ListOpenLineageRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_ListOpenLineageRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).ListOpenLineageRuns(ctx, req.(*ListOpenLineageRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_GetOpenLineageRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpenLineageRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).GetOpenLineageRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_GetOpenLineageRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).GetOpenLineageRun(ctx, req.(*GetOpenLineageRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_CreateNamespaceMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).CreateNamespaceMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_CreateNamespaceMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).CreateNamespaceMapping(ctx, req.(*CreateNamespaceMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_ListNamespaceMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespaceMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).ListNamespaceMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_ListNamespaceMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).ListNamespaceMapping(ctx, req.(*ListNamespaceMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_UpdateNamespaceMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNamespaceMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).UpdateNamespaceMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_UpdateNamespaceMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).UpdateNamespaceMapping(ctx, req.(*UpdateNamespaceMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_DeleteNamespaceMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).DeleteNamespaceMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_DeleteNamespaceMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).DeleteNamespaceMapping(ctx, req.(*DeleteNamespaceMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_CreateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).CreateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_CreateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).CreateAPIKey(ctx, req.(*CreateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_ListAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).ListAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_ListAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).ListAPIKey(ctx, req.(*ListAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenLineageService_RevokeAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenLineageServiceServer).RevokeAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenLineageService_RevokeAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenLineageServiceServer).RevokeAPIKey(ctx, req.(*RevokeAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenLineageService_ServiceDesc is the grpc.ServiceDesc for OpenLineageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenLineageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metaxisdata.v1.OpenLineageService",
	HandlerType: (*OpenLineageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOpenLineageTasks",
			Handler:    _OpenLineageService_ListOpenLineageTasks_Handler,
		},
		{
			MethodName: "ListOpenLineageDatasets",
			Handler:    _OpenLineageService_ListOpenLineageDatasets_Handler,
		},
		{
			MethodName: "GetOpenLineageDataset",
			Handler:    _OpenLineageService_GetOpenLineageDataset_Handler,
		},
		{
			MethodName: "GetOpenLineageTask",
			Handler:    _OpenLineageService_GetOpenLineageTask_Handler,
		},
		{
			MethodName: "ListOpenLineageRuns",
			Handler:    _OpenLineageService_ListOpenLineageRuns_Handler,
		},
		{
			MethodName: "GetOpenLineageRun",
			Handler:    _OpenLineageService_GetOpenLineageRun_Handler,
		},
		{
			MethodName: "CreateNamespaceMapping",
			Handler:    _OpenLineageService_CreateNamespaceMapping_Handler,
		},
		{
			MethodName: "ListNamespaceMapping",
			Handler:    _OpenLineageService_ListNamespaceMapping_Handler,
		},
		{
			MethodName: "UpdateNamespaceMapping",
			Handler:    _OpenLineageService_UpdateNamespaceMapping_Handler,
		},
		{
			MethodName: "DeleteNamespaceMapping",
			Handler:    _OpenLineageService_DeleteNamespaceMapping_Handler,
		},
		{
			MethodName: "CreateAPIKey",
			Handler:    _OpenLineageService_CreateAPIKey_Handler,
		},
		{
			MethodName: "ListAPIKey",
			Handler:    _OpenLineageService_ListAPIKey_Handler,
		},
		{
			MethodName: "RevokeAPIKey",
			Handler:    _OpenLineageService_RevokeAPIKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/openlineage_service.proto",
}
