// @generated by protoc-gen-es v2.5.2
// @generated from file v1/auth_service.proto (package metaxisdata.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { User } from "./user_service_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file v1/auth_service.proto.
 */
export declare const file_v1_auth_service: GenFile;

/**
 * @generated from message metaxisdata.v1.LoginRequest
 */
export declare type LoginRequest = Message<"metaxisdata.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * If web is set, we will set access token, refresh token, and user to the cookie.
   *
   * @generated from field: bool web = 3;
   */
  web: boolean;

  /**
   * The name of the identity provider.
   * Format: idps/{idp}
   *
   * @generated from field: string idp_name = 4;
   */
  idpName: string;

  /**
   * The idp_context is using to get the user information from identity provider.
   *
   * @generated from field: metaxisdata.v1.IdentityProviderContext idp_context = 5;
   */
  idpContext?: IdentityProviderContext;
};

/**
 * Describes the message metaxisdata.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export declare const LoginRequestSchema: GenMessage<LoginRequest>;

/**
 * @generated from message metaxisdata.v1.IdentityProviderContext
 */
export declare type IdentityProviderContext = Message<"metaxisdata.v1.IdentityProviderContext"> & {
  /**
   * @generated from oneof metaxisdata.v1.IdentityProviderContext.context
   */
  context: {
    /**
     * @generated from field: metaxisdata.v1.OAuth2IdentityProviderContext oauth2_context = 1;
     */
    value: OAuth2IdentityProviderContext;
    case: "oauth2Context";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message metaxisdata.v1.IdentityProviderContext.
 * Use `create(IdentityProviderContextSchema)` to create a new message.
 */
export declare const IdentityProviderContextSchema: GenMessage<IdentityProviderContext>;

/**
 * @generated from message metaxisdata.v1.OAuth2IdentityProviderContext
 */
export declare type OAuth2IdentityProviderContext = Message<"metaxisdata.v1.OAuth2IdentityProviderContext"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;
};

/**
 * Describes the message metaxisdata.v1.OAuth2IdentityProviderContext.
 * Use `create(OAuth2IdentityProviderContextSchema)` to create a new message.
 */
export declare const OAuth2IdentityProviderContextSchema: GenMessage<OAuth2IdentityProviderContext>;

/**
 * @generated from message metaxisdata.v1.LoginResponse
 */
export declare type LoginResponse = Message<"metaxisdata.v1.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: bool require_reset_password = 3;
   */
  requireResetPassword: boolean;

  /**
   * The user of successful login.
   *
   * @generated from field: metaxisdata.v1.User user = 4;
   */
  user?: User;
};

/**
 * Describes the message metaxisdata.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export declare const LoginResponseSchema: GenMessage<LoginResponse>;

/**
 * @generated from message metaxisdata.v1.LogoutRequest
 */
export declare type LogoutRequest = Message<"metaxisdata.v1.LogoutRequest"> & {
};

/**
 * Describes the message metaxisdata.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export declare const LogoutRequestSchema: GenMessage<LogoutRequest>;

/**
 * @generated from service metaxisdata.v1.AuthService
 */
export declare const AuthService: GenService<{
  /**
   * Permissions required: None
   *
   * @generated from rpc metaxisdata.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Permissions required: None
   *
   * @generated from rpc metaxisdata.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof EmptySchema;
  },
}>;

