// @generated by protoc-gen-es v2.5.2
// @generated from file v1/common.proto (package metaxisdata.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file v1/common.proto.
 */
export const file_v1_common = /*@__PURE__*/
  fileDesc("Cg92MS9jb21tb24ucHJvdG8SDm1ldGF4aXNkYXRhLnYxKjcKBVN0YXRlEhUKEVNUQVRFX1VOU1BFQ0lGSUVEEAASCgoGQUNUSVZFEAESCwoHREVMRVRFRBACKr4CCgZFbmdpbmUSFgoSRU5HSU5FX1VOU1BFQ0lGSUVEEAASCQoFTVNTUUwQARIJCgVNWVNRTBACEgwKCFBPU1RHUkVTEAMSCAoEVElEQhAGEgsKB01BUklBREIQDRINCglPQ0VBTkJBU0UQDhINCglTVEFSUk9DS1MQDxIJCgVET1JJUxAQIgQIBBAFIgQIBxAMIgQIERAcKgpDTElDS0hPVVNFKglTTk9XRkxBS0UqBlNRTElURSoHTU9OR09EQioFUkVESVMqBk9SQUNMRSoHU1BBTk5FUioIUkVEU0hJRlQqBEhJVkUqDUVMQVNUSUNTRUFSQ0gqCEJJR1FVRVJZKghEWU5BTU9EQioKREFUQUJSSUNLUyoLQ09DS1JPQUNIREIqCENPU01PU0RCKgVUUklOTyoJQ0FTU0FORFJBQjZaNGdpdGh1Yi5jb20vUmFueHkvbWV0YXhpc2RhdGEvYmFja2VuZC9nZW5lcmF0ZWQtZ28vdjFiBnByb3RvMw");

/**
 * Describes the enum metaxisdata.v1.State.
 */
export const StateSchema = /*@__PURE__*/
  enumDesc(file_v1_common, 0);

/**
 * @generated from enum metaxisdata.v1.State
 */
export const State = /*@__PURE__*/
  tsEnum(StateSchema);

/**
 * Describes the enum metaxisdata.v1.Engine.
 */
export const EngineSchema = /*@__PURE__*/
  enumDesc(file_v1_common, 1);

/**
 * Engine is the database engine of an instance. Only the engines the product
 * actually supports are kept: MySQL-compatible ones (MySQL, TiDB, MariaDB,
 * OceanBase, StarRocks, Doris), PostgreSQL and SQL Server. The other removed
 * values keep their numbers reserved so they can never be silently reused for
 * something else.
 *
 * @generated from enum metaxisdata.v1.Engine
 */
export const Engine = /*@__PURE__*/
  tsEnum(EngineSchema);

