// @generated by protoc-gen-es v2.5.2
// @generated from file v1/environment_service.proto (package metaxisdata.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, FieldMask } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file v1/environment_service.proto.
 */
export declare const file_v1_environment_service: GenFile;

/**
 * @generated from message metaxisdata.v1.Environment
 */
export declare type Environment = Message<"metaxisdata.v1.Environment"> & {
  /**
   * The resource name. Format: environments/{id}. Output only: the id is
   * derived from the title on create and cannot be changed afterwards.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The display name, e.g. "Production".
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * A preset palette key controlling the badge color. One of: slate, blue,
   * green, amber, orange, red, violet, pink. Empty on create lets the server
   * pick a stable default.
   *
   * @generated from field: string color = 3;
   */
  color: string;

  /**
   * Free-form labels attached to the environment.
   *
   * @generated from field: map<string, string> tags = 4;
   */
  tags: { [key: string]: string };

  /**
   * The number of live instances assigned to this environment. Output only, and
   * populated by ListEnvironments only. DeleteEnvironment is refused while it
   * is non-zero.
   *
   * @generated from field: int32 instance_count = 5;
   */
  instanceCount: number;
};

/**
 * Describes the message metaxisdata.v1.Environment.
 * Use `create(EnvironmentSchema)` to create a new message.
 */
export declare const EnvironmentSchema: GenMessage<Environment>;

/**
 * @generated from message metaxisdata.v1.ListEnvironmentsRequest
 */
export declare type ListEnvironmentsRequest = Message<"metaxisdata.v1.ListEnvironmentsRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message metaxisdata.v1.ListEnvironmentsRequest.
 * Use `create(ListEnvironmentsRequestSchema)` to create a new message.
 */
export declare const ListEnvironmentsRequestSchema: GenMessage<ListEnvironmentsRequest>;

/**
 * @generated from message metaxisdata.v1.ListEnvironmentsResponse
 */
export declare type ListEnvironmentsResponse = Message<"metaxisdata.v1.ListEnvironmentsResponse"> & {
  /**
   * @generated from field: repeated metaxisdata.v1.Environment environments = 1;
   */
  environments: Environment[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message metaxisdata.v1.ListEnvironmentsResponse.
 * Use `create(ListEnvironmentsResponseSchema)` to create a new message.
 */
export declare const ListEnvironmentsResponseSchema: GenMessage<ListEnvironmentsResponse>;

/**
 * @generated from message metaxisdata.v1.CreateEnvironmentRequest
 */
export declare type CreateEnvironmentRequest = Message<"metaxisdata.v1.CreateEnvironmentRequest"> & {
  /**
   * The environment to create. The title is required; name and color are
   * ignored on create (the server derives them).
   *
   * @generated from field: metaxisdata.v1.Environment environment = 1;
   */
  environment?: Environment;
};

/**
 * Describes the message metaxisdata.v1.CreateEnvironmentRequest.
 * Use `create(CreateEnvironmentRequestSchema)` to create a new message.
 */
export declare const CreateEnvironmentRequestSchema: GenMessage<CreateEnvironmentRequest>;

/**
 * @generated from message metaxisdata.v1.UpdateEnvironmentRequest
 */
export declare type UpdateEnvironmentRequest = Message<"metaxisdata.v1.UpdateEnvironmentRequest"> & {
  /**
   * The environment to update.
   *
   * @generated from field: metaxisdata.v1.Environment environment = 1;
   */
  environment?: Environment;

  /**
   * The fields to update: title, color, tags.
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message metaxisdata.v1.UpdateEnvironmentRequest.
 * Use `create(UpdateEnvironmentRequestSchema)` to create a new message.
 */
export declare const UpdateEnvironmentRequestSchema: GenMessage<UpdateEnvironmentRequest>;

/**
 * @generated from message metaxisdata.v1.DeleteEnvironmentRequest
 */
export declare type DeleteEnvironmentRequest = Message<"metaxisdata.v1.DeleteEnvironmentRequest"> & {
  /**
   * The environment resource name. Format: environments/{id}.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message metaxisdata.v1.DeleteEnvironmentRequest.
 * Use `create(DeleteEnvironmentRequestSchema)` to create a new message.
 */
export declare const DeleteEnvironmentRequestSchema: GenMessage<DeleteEnvironmentRequest>;

/**
 * EnvironmentService manages the workspace's environments. An environment is a
 * small, workspace-scoped resource ("environments/{id}") that instances are
 * tagged with; databases inherit their instance's environment.
 *
 * Environments are stored in the ENVIRONMENT workspace setting, not in a table
 * of their own. The id is derived from the title on create and is immutable:
 * instances store the raw id, so renaming only changes the display title.
 *
 * @generated from service metaxisdata.v1.EnvironmentService
 */
export declare const EnvironmentService: GenService<{
  /**
   * List the workspace environments.
   *
   * Readable by every workspace member: the instance forms and the metadata
   * filters need the list, and those pages are open to every member.
   *
   * @generated from rpc metaxisdata.v1.EnvironmentService.ListEnvironments
   */
  listEnvironments: {
    methodKind: "unary";
    input: typeof ListEnvironmentsRequestSchema;
    output: typeof ListEnvironmentsResponseSchema;
  },
  /**
   * Create an environment.
   *
   * @generated from rpc metaxisdata.v1.EnvironmentService.CreateEnvironment
   */
  createEnvironment: {
    methodKind: "unary";
    input: typeof CreateEnvironmentRequestSchema;
    output: typeof EnvironmentSchema;
  },
  /**
   * Update an environment. Only title, color and tags are mutable; the resource
   * name (the id) is not.
   *
   * @generated from rpc metaxisdata.v1.EnvironmentService.UpdateEnvironment
   */
  updateEnvironment: {
    methodKind: "unary";
    input: typeof UpdateEnvironmentRequestSchema;
    output: typeof EnvironmentSchema;
  },
  /**
   * Delete an environment. An environment still assigned to a live instance
   * cannot be deleted.
   *
   * @generated from rpc metaxisdata.v1.EnvironmentService.DeleteEnvironment
   */
  deleteEnvironment: {
    methodKind: "unary";
    input: typeof DeleteEnvironmentRequestSchema;
    output: typeof EmptySchema;
  },
}>;

