// @generated by protoc-gen-es v2.5.2
// @generated from file v1/llm_service.proto (package metaxisdata.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file v1/llm_service.proto.
 */
export declare const file_v1_llm_service: GenFile;

/**
 * @generated from message metaxisdata.v1.LlmProviderDefinition
 */
export declare type LlmProviderDefinition = Message<"metaxisdata.v1.LlmProviderDefinition"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: string default_base_url = 4;
   */
  defaultBaseUrl: string;
};

/**
 * Describes the message metaxisdata.v1.LlmProviderDefinition.
 * Use `create(LlmProviderDefinitionSchema)` to create a new message.
 */
export declare const LlmProviderDefinitionSchema: GenMessage<LlmProviderDefinition>;

/**
 * @generated from message metaxisdata.v1.LlmProviderModel
 */
export declare type LlmProviderModel = Message<"metaxisdata.v1.LlmProviderModel"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: bool enabled = 2;
   */
  enabled: boolean;
};

/**
 * Describes the message metaxisdata.v1.LlmProviderModel.
 * Use `create(LlmProviderModelSchema)` to create a new message.
 */
export declare const LlmProviderModelSchema: GenMessage<LlmProviderModel>;

/**
 * @generated from message metaxisdata.v1.LlmProviderProfile
 */
export declare type LlmProviderProfile = Message<"metaxisdata.v1.LlmProviderProfile"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: metaxisdata.v1.LLMProviderType type = 3;
   */
  type: LLMProviderType;

  /**
   * @generated from field: string base_url = 4;
   */
  baseUrl: string;

  /**
   * @generated from field: string api_key = 5;
   */
  apiKey: string;

  /**
   * @generated from field: repeated metaxisdata.v1.LlmProviderModel models = 6;
   */
  models: LlmProviderModel[];

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 7;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 8;
   */
  updateTime?: Timestamp;

  /**
   * @generated from field: string masked_api_key = 9;
   */
  maskedApiKey: string;
};

/**
 * Describes the message metaxisdata.v1.LlmProviderProfile.
 * Use `create(LlmProviderProfileSchema)` to create a new message.
 */
export declare const LlmProviderProfileSchema: GenMessage<LlmProviderProfile>;

/**
 * @generated from message metaxisdata.v1.ListLLMProviderProfilesRequest
 */
export declare type ListLLMProviderProfilesRequest = Message<"metaxisdata.v1.ListLLMProviderProfilesRequest"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message metaxisdata.v1.ListLLMProviderProfilesRequest.
 * Use `create(ListLLMProviderProfilesRequestSchema)` to create a new message.
 */
export declare const ListLLMProviderProfilesRequestSchema: GenMessage<ListLLMProviderProfilesRequest>;

/**
 * @generated from message metaxisdata.v1.ListLLMProviderProfilesResponse
 */
export declare type ListLLMProviderProfilesResponse = Message<"metaxisdata.v1.ListLLMProviderProfilesResponse"> & {
  /**
   * @generated from field: repeated metaxisdata.v1.LlmProviderProfile profiles = 1;
   */
  profiles: LlmProviderProfile[];

  /**
   * @generated from field: repeated metaxisdata.v1.LlmProviderDefinition definitions = 2;
   */
  definitions: LlmProviderDefinition[];

  /**
   * @generated from field: string next_page_token = 3;
   */
  nextPageToken: string;
};

/**
 * Describes the message metaxisdata.v1.ListLLMProviderProfilesResponse.
 * Use `create(ListLLMProviderProfilesResponseSchema)` to create a new message.
 */
export declare const ListLLMProviderProfilesResponseSchema: GenMessage<ListLLMProviderProfilesResponse>;

/**
 * @generated from message metaxisdata.v1.CreateLLMProviderProfileRequest
 */
export declare type CreateLLMProviderProfileRequest = Message<"metaxisdata.v1.CreateLLMProviderProfileRequest"> & {
  /**
   * @generated from field: metaxisdata.v1.LlmProviderProfile profile = 1;
   */
  profile?: LlmProviderProfile;
};

/**
 * Describes the message metaxisdata.v1.CreateLLMProviderProfileRequest.
 * Use `create(CreateLLMProviderProfileRequestSchema)` to create a new message.
 */
export declare const CreateLLMProviderProfileRequestSchema: GenMessage<CreateLLMProviderProfileRequest>;

/**
 * @generated from message metaxisdata.v1.UpdateLLMProviderProfileRequest
 */
export declare type UpdateLLMProviderProfileRequest = Message<"metaxisdata.v1.UpdateLLMProviderProfileRequest"> & {
  /**
   * @generated from field: metaxisdata.v1.LlmProviderProfile profile = 1;
   */
  profile?: LlmProviderProfile;

  /**
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message metaxisdata.v1.UpdateLLMProviderProfileRequest.
 * Use `create(UpdateLLMProviderProfileRequestSchema)` to create a new message.
 */
export declare const UpdateLLMProviderProfileRequestSchema: GenMessage<UpdateLLMProviderProfileRequest>;

/**
 * @generated from message metaxisdata.v1.DeleteLLMProviderProfileRequest
 */
export declare type DeleteLLMProviderProfileRequest = Message<"metaxisdata.v1.DeleteLLMProviderProfileRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message metaxisdata.v1.DeleteLLMProviderProfileRequest.
 * Use `create(DeleteLLMProviderProfileRequestSchema)` to create a new message.
 */
export declare const DeleteLLMProviderProfileRequestSchema: GenMessage<DeleteLLMProviderProfileRequest>;

/**
 * @generated from message metaxisdata.v1.FetchLLMModelsRequest
 */
export declare type FetchLLMModelsRequest = Message<"metaxisdata.v1.FetchLLMModelsRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string api_key = 2;
   */
  apiKey: string;

  /**
   * @generated from field: metaxisdata.v1.LLMProviderType provider_type = 3;
   */
  providerType: LLMProviderType;
};

/**
 * Describes the message metaxisdata.v1.FetchLLMModelsRequest.
 * Use `create(FetchLLMModelsRequestSchema)` to create a new message.
 */
export declare const FetchLLMModelsRequestSchema: GenMessage<FetchLLMModelsRequest>;

/**
 * @generated from message metaxisdata.v1.FetchLLMModelsResponse
 */
export declare type FetchLLMModelsResponse = Message<"metaxisdata.v1.FetchLLMModelsResponse"> & {
  /**
   * @generated from field: repeated string model_ids = 1;
   */
  modelIds: string[];
};

/**
 * Describes the message metaxisdata.v1.FetchLLMModelsResponse.
 * Use `create(FetchLLMModelsResponseSchema)` to create a new message.
 */
export declare const FetchLLMModelsResponseSchema: GenMessage<FetchLLMModelsResponse>;

/**
 * @generated from enum metaxisdata.v1.LLMProviderType
 */
export enum LLMProviderType {
  /**
   * @generated from enum value: LLM_PROVIDER_TYPE_UNSPECIFIED = 0;
   */
  LLM_PROVIDER_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: LLM_PROVIDER_TYPE_OPENAI = 1;
   */
  LLM_PROVIDER_TYPE_OPENAI = 1,

  /**
   * @generated from enum value: LLM_PROVIDER_TYPE_DEEPSEEK = 2;
   */
  LLM_PROVIDER_TYPE_DEEPSEEK = 2,

  /**
   * @generated from enum value: LLM_PROVIDER_TYPE_OPENROUTER = 3;
   */
  LLM_PROVIDER_TYPE_OPENROUTER = 3,

  /**
   * @generated from enum value: LLM_PROVIDER_TYPE_CUSTOM = 4;
   */
  LLM_PROVIDER_TYPE_CUSTOM = 4,
}

/**
 * Describes the enum metaxisdata.v1.LLMProviderType.
 */
export declare const LLMProviderTypeSchema: GenEnum<LLMProviderType>;

/**
 * @generated from service metaxisdata.v1.LLMService
 */
export declare const LLMService: GenService<{
  /**
   * @generated from rpc metaxisdata.v1.LLMService.ListLLMProviderProfiles
   */
  listLLMProviderProfiles: {
    methodKind: "unary";
    input: typeof ListLLMProviderProfilesRequestSchema;
    output: typeof ListLLMProviderProfilesResponseSchema;
  },
  /**
   * @generated from rpc metaxisdata.v1.LLMService.CreateLLMProviderProfile
   */
  createLLMProviderProfile: {
    methodKind: "unary";
    input: typeof CreateLLMProviderProfileRequestSchema;
    output: typeof LlmProviderProfileSchema;
  },
  /**
   * @generated from rpc metaxisdata.v1.LLMService.UpdateLLMProviderProfile
   */
  updateLLMProviderProfile: {
    methodKind: "unary";
    input: typeof UpdateLLMProviderProfileRequestSchema;
    output: typeof LlmProviderProfileSchema;
  },
  /**
   * @generated from rpc metaxisdata.v1.LLMService.DeleteLLMProviderProfile
   */
  deleteLLMProviderProfile: {
    methodKind: "unary";
    input: typeof DeleteLLMProviderProfileRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc metaxisdata.v1.LLMService.FetchLLMModels
   */
  fetchLLMModels: {
    methodKind: "unary";
    input: typeof FetchLLMModelsRequestSchema;
    output: typeof FetchLLMModelsResponseSchema;
  },
}>;

