// @generated by protoc-gen-es v2.5.2
// @generated from file v1/notification_service.proto (package metaxisdata.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file v1/notification_service.proto.
 */
export declare const file_v1_notification_service: GenFile;

/**
 * Notification is one in-app message for one recipient.
 *
 * @generated from message metaxisdata.v1.Notification
 */
export declare type Notification = Message<"metaxisdata.v1.Notification"> & {
  /**
   * Format: workspaces/{workspace}/notifications/{id}
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 2;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: metaxisdata.v1.NotificationType type = 3;
   */
  type: NotificationType;

  /**
   * @generated from field: metaxisdata.v1.NotificationSeverity severity = 4;
   */
  severity: NotificationSeverity;

  /**
   * When the recipient read it. Unset means unread.
   *
   * @generated from field: google.protobuf.Timestamp read_time = 5;
   */
  readTime?: Timestamp;

  /**
   * The body, interpreted by type. The server stores no prose: the client
   * renders the localized text from the detail and its own catalogs, so a
   * message reads in the user's language and an unknown type degrades to a
   * generic sentence instead of an empty row.
   *
   * @generated from oneof metaxisdata.v1.Notification.detail
   */
  detail: {
    /**
     * @generated from field: metaxisdata.v1.SchemaSyncDetail schema_sync = 6;
     */
    value: SchemaSyncDetail;
    case: "schemaSync";
  } | {
    /**
     * @generated from field: metaxisdata.v1.OpenLineageDetail openlineage = 7;
     */
    value: OpenLineageDetail;
    case: "openlineage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message metaxisdata.v1.Notification.
 * Use `create(NotificationSchema)` to create a new message.
 */
export declare const NotificationSchema: GenMessage<Notification>;

/**
 * SchemaSyncDetail reports one sync operation: the instance metadata step plus
 * every database that operation queued.
 *
 * @generated from message metaxisdata.v1.SchemaSyncDetail
 */
export declare type SchemaSyncDetail = Message<"metaxisdata.v1.SchemaSyncDetail"> & {
  /**
   * Format: instances/{instance}
   *
   * @generated from field: string instance = 1;
   */
  instance: string;

  /**
   * The instance's display name, so the client can render the message without a
   * second read.
   *
   * @generated from field: string instance_title = 2;
   */
  instanceTitle: string;

  /**
   * @generated from field: metaxisdata.v1.SyncTrigger trigger = 3;
   */
  trigger: SyncTrigger;

  /**
   * Why the instance metadata step failed. Empty when it succeeded.
   *
   * @generated from field: string instance_error = 4;
   */
  instanceError: string;

  /**
   * The databases this message names, each with its outcome: the ones that failed
   * or never reported for an instance-wide sync, and the database itself for a sync
   * of one database. Successful databases are counted rather than listed.
   *
   * @generated from field: repeated metaxisdata.v1.SyncDatabaseResult databases = 5;
   */
  databases: SyncDatabaseResult[];

  /**
   * @generated from field: int32 succeeded_count = 6;
   */
  succeededCount: number;

  /**
   * @generated from field: int32 failed_count = 7;
   */
  failedCount: number;

  /**
   * @generated from field: int32 unfinished_count = 8;
   */
  unfinishedCount: number;
};

/**
 * Describes the message metaxisdata.v1.SchemaSyncDetail.
 * Use `create(SchemaSyncDetailSchema)` to create a new message.
 */
export declare const SchemaSyncDetailSchema: GenMessage<SchemaSyncDetail>;

/**
 * SyncDatabaseResult is one database's outcome in a schema sync operation.
 *
 * @generated from message metaxisdata.v1.SyncDatabaseResult
 */
export declare type SyncDatabaseResult = Message<"metaxisdata.v1.SyncDatabaseResult"> & {
  /**
   * Format: instances/{instance}/databases/{database}
   *
   * @generated from field: string database = 1;
   */
  database: string;

  /**
   * @generated from field: metaxisdata.v1.SyncDatabaseState state = 2;
   */
  state: SyncDatabaseState;

  /**
   * The sync error. Empty for UNFINISHED.
   *
   * @generated from field: string error = 3;
   */
  error: string;
};

/**
 * Describes the message metaxisdata.v1.SyncDatabaseResult.
 * Use `create(SyncDatabaseResultSchema)` to create a new message.
 */
export declare const SyncDatabaseResultSchema: GenMessage<SyncDatabaseResult>;

/**
 * OpenLineageDetail reports an OpenLineage ingestion failure, or a dataset that
 * fell through to an external dataset.
 *
 * @generated from message metaxisdata.v1.OpenLineageDetail
 */
export declare type OpenLineageDetail = Message<"metaxisdata.v1.OpenLineageDetail"> & {
  /**
   * @generated from field: metaxisdata.v1.OpenLineageFailureKind kind = 1;
   */
  kind: OpenLineageFailureKind;

  /**
   * The namespace named by the event. Empty when the event did not parse.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * @generated from field: string job = 3;
   */
  job: string;

  /**
   * @generated from field: string run_id = 4;
   */
  runId: string;

  /**
   * The dataset that did not resolve. Only set for NAMESPACE_UNMAPPED.
   *
   * @generated from field: string dataset = 5;
   */
  dataset: string;

  /**
   * The masked identifier of the ingestion key that submitted the request,
   * never the key itself.
   *
   * @generated from field: string api_key = 6;
   */
  apiKey: string;

  /**
   * How many events the request carried and how many of them failed.
   *
   * @generated from field: int32 received_count = 7;
   */
  receivedCount: number;

  /**
   * @generated from field: int32 failed_count = 8;
   */
  failedCount: number;

  /**
   * @generated from field: string error = 9;
   */
  error: string;
};

/**
 * Describes the message metaxisdata.v1.OpenLineageDetail.
 * Use `create(OpenLineageDetailSchema)` to create a new message.
 */
export declare const OpenLineageDetailSchema: GenMessage<OpenLineageDetail>;

/**
 * @generated from message metaxisdata.v1.ListNotificationsRequest
 */
export declare type ListNotificationsRequest = Message<"metaxisdata.v1.ListNotificationsRequest"> & {
  /**
   * Format: workspaces/{workspace}. "workspaces/-" is the current workspace.
   *
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * The maximum number of notifications to return. If unspecified, at most 50
   * are returned. The maximum value is 1000; values above 1000 are coerced to
   * 1000.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * A page token, received from a previous ListNotifications call. Provide this
   * to retrieve the subsequent page.
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * Return only unread notifications.
   *
   * @generated from field: bool unread_only = 4;
   */
  unreadOnly: boolean;
};

/**
 * Describes the message metaxisdata.v1.ListNotificationsRequest.
 * Use `create(ListNotificationsRequestSchema)` to create a new message.
 */
export declare const ListNotificationsRequestSchema: GenMessage<ListNotificationsRequest>;

/**
 * @generated from message metaxisdata.v1.ListNotificationsResponse
 */
export declare type ListNotificationsResponse = Message<"metaxisdata.v1.ListNotificationsResponse"> & {
  /**
   * @generated from field: repeated metaxisdata.v1.Notification notifications = 1;
   */
  notifications: Notification[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message metaxisdata.v1.ListNotificationsResponse.
 * Use `create(ListNotificationsResponseSchema)` to create a new message.
 */
export declare const ListNotificationsResponseSchema: GenMessage<ListNotificationsResponse>;

/**
 * @generated from message metaxisdata.v1.GetUnreadNotificationCountRequest
 */
export declare type GetUnreadNotificationCountRequest = Message<"metaxisdata.v1.GetUnreadNotificationCountRequest"> & {
  /**
   * Format: workspaces/{workspace}. "workspaces/-" is the current workspace.
   *
   * @generated from field: string parent = 1;
   */
  parent: string;
};

/**
 * Describes the message metaxisdata.v1.GetUnreadNotificationCountRequest.
 * Use `create(GetUnreadNotificationCountRequestSchema)` to create a new message.
 */
export declare const GetUnreadNotificationCountRequestSchema: GenMessage<GetUnreadNotificationCountRequest>;

/**
 * @generated from message metaxisdata.v1.GetUnreadNotificationCountResponse
 */
export declare type GetUnreadNotificationCountResponse = Message<"metaxisdata.v1.GetUnreadNotificationCountResponse"> & {
  /**
   * @generated from field: int32 unread_count = 1;
   */
  unreadCount: number;
};

/**
 * Describes the message metaxisdata.v1.GetUnreadNotificationCountResponse.
 * Use `create(GetUnreadNotificationCountResponseSchema)` to create a new message.
 */
export declare const GetUnreadNotificationCountResponseSchema: GenMessage<GetUnreadNotificationCountResponse>;

/**
 * @generated from message metaxisdata.v1.BatchMarkNotificationsReadRequest
 */
export declare type BatchMarkNotificationsReadRequest = Message<"metaxisdata.v1.BatchMarkNotificationsReadRequest"> & {
  /**
   * Format: workspaces/{workspace}. "workspaces/-" is the current workspace.
   *
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * Format: workspaces/{workspace}/notifications/{id}
   *
   * @generated from field: repeated string names = 2;
   */
  names: string[];
};

/**
 * Describes the message metaxisdata.v1.BatchMarkNotificationsReadRequest.
 * Use `create(BatchMarkNotificationsReadRequestSchema)` to create a new message.
 */
export declare const BatchMarkNotificationsReadRequestSchema: GenMessage<BatchMarkNotificationsReadRequest>;

/**
 * @generated from message metaxisdata.v1.MarkAllNotificationsReadRequest
 */
export declare type MarkAllNotificationsReadRequest = Message<"metaxisdata.v1.MarkAllNotificationsReadRequest"> & {
  /**
   * Format: workspaces/{workspace}. "workspaces/-" is the current workspace.
   *
   * @generated from field: string parent = 1;
   */
  parent: string;
};

/**
 * Describes the message metaxisdata.v1.MarkAllNotificationsReadRequest.
 * Use `create(MarkAllNotificationsReadRequestSchema)` to create a new message.
 */
export declare const MarkAllNotificationsReadRequestSchema: GenMessage<MarkAllNotificationsReadRequest>;

/**
 * @generated from message metaxisdata.v1.DeleteNotificationRequest
 */
export declare type DeleteNotificationRequest = Message<"metaxisdata.v1.DeleteNotificationRequest"> & {
  /**
   * Format: workspaces/{workspace}/notifications/{id}
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message metaxisdata.v1.DeleteNotificationRequest.
 * Use `create(DeleteNotificationRequestSchema)` to create a new message.
 */
export declare const DeleteNotificationRequestSchema: GenMessage<DeleteNotificationRequest>;

/**
 * @generated from message metaxisdata.v1.SubscribeNotificationsRequest
 */
export declare type SubscribeNotificationsRequest = Message<"metaxisdata.v1.SubscribeNotificationsRequest"> & {
  /**
   * Format: workspaces/{workspace}. "workspaces/-" is the current workspace.
   *
   * @generated from field: string parent = 1;
   */
  parent: string;
};

/**
 * Describes the message metaxisdata.v1.SubscribeNotificationsRequest.
 * Use `create(SubscribeNotificationsRequestSchema)` to create a new message.
 */
export declare const SubscribeNotificationsRequestSchema: GenMessage<SubscribeNotificationsRequest>;

/**
 * @generated from message metaxisdata.v1.SubscribeNotificationsResponse
 */
export declare type SubscribeNotificationsResponse = Message<"metaxisdata.v1.SubscribeNotificationsResponse"> & {
  /**
   * @generated from oneof metaxisdata.v1.SubscribeNotificationsResponse.event
   */
  event: {
    /**
     * A notification written while the caller was connected.
     *
     * @generated from field: metaxisdata.v1.NotificationEvent notification = 1;
     */
    value: NotificationEvent;
    case: "notification";
  } | {
    /**
     * An empty message sent while nothing happens, so a proxy does not end an idle
     * stream — nginx would after proxy_read_timeout, which is 60 seconds by
     * default. The client ignores it.
     *
     * @generated from field: metaxisdata.v1.KeepAlive keep_alive = 2;
     */
    value: KeepAlive;
    case: "keepAlive";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message metaxisdata.v1.SubscribeNotificationsResponse.
 * Use `create(SubscribeNotificationsResponseSchema)` to create a new message.
 */
export declare const SubscribeNotificationsResponseSchema: GenMessage<SubscribeNotificationsResponse>;

/**
 * @generated from message metaxisdata.v1.NotificationEvent
 */
export declare type NotificationEvent = Message<"metaxisdata.v1.NotificationEvent"> & {
  /**
   * @generated from field: metaxisdata.v1.Notification notification = 1;
   */
  notification?: Notification;

  /**
   * The recipient's unread count after this notification was written. Absent when
   * it could not be read, in which case the client asks for the count itself
   * rather than showing a wrong number.
   *
   * @generated from field: optional int32 unread_count = 2;
   */
  unreadCount?: number;
};

/**
 * Describes the message metaxisdata.v1.NotificationEvent.
 * Use `create(NotificationEventSchema)` to create a new message.
 */
export declare const NotificationEventSchema: GenMessage<NotificationEvent>;

/**
 * KeepAlive is the notification stream's heartbeat. It carries no data.
 *
 * @generated from message metaxisdata.v1.KeepAlive
 */
export declare type KeepAlive = Message<"metaxisdata.v1.KeepAlive"> & {
};

/**
 * Describes the message metaxisdata.v1.KeepAlive.
 * Use `create(KeepAliveSchema)` to create a new message.
 */
export declare const KeepAliveSchema: GenMessage<KeepAlive>;

/**
 * NotificationType is what a notification is about. It selects which detail
 * message the notification carries.
 *
 * @generated from enum metaxisdata.v1.NotificationType
 */
export enum NotificationType {
  /**
   * @generated from enum value: NOTIFICATION_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The outcome of one schema sync operation.
   *
   * @generated from enum value: NOTIFICATION_TYPE_SCHEMA_SYNC = 1;
   */
  SCHEMA_SYNC = 1,

  /**
   * An OpenLineage ingestion failure, or a dataset that could not be matched
   * to a registered instance.
   *
   * @generated from enum value: NOTIFICATION_TYPE_OPENLINEAGE = 2;
   */
  OPENLINEAGE = 2,
}

/**
 * Describes the enum metaxisdata.v1.NotificationType.
 */
export declare const NotificationTypeSchema: GenEnum<NotificationType>;

/**
 * NotificationSeverity ranks a notification for its recipient.
 *
 * @generated from enum metaxisdata.v1.NotificationSeverity
 */
export enum NotificationSeverity {
  /**
   * @generated from enum value: NOTIFICATION_SEVERITY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: NOTIFICATION_SEVERITY_INFO = 1;
   */
  INFO = 1,

  /**
   * @generated from enum value: NOTIFICATION_SEVERITY_WARNING = 2;
   */
  WARNING = 2,

  /**
   * @generated from enum value: NOTIFICATION_SEVERITY_ERROR = 3;
   */
  ERROR = 3,
}

/**
 * Describes the enum metaxisdata.v1.NotificationSeverity.
 */
export declare const NotificationSeveritySchema: GenEnum<NotificationSeverity>;

/**
 * SyncTrigger is what started the sync operation a notification reports.
 *
 * @generated from enum metaxisdata.v1.SyncTrigger
 */
export enum SyncTrigger {
  /**
   * @generated from enum value: SYNC_TRIGGER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * A user asked for it. The initiator is the recipient.
   *
   * @generated from enum value: SYNC_TRIGGER_MANUAL = 1;
   */
  MANUAL = 1,

  /**
   * The periodic scan asked for it, so there is no initiator and the workspace
   * administrators are the recipients.
   *
   * @generated from enum value: SYNC_TRIGGER_BACKGROUND = 2;
   */
  BACKGROUND = 2,
}

/**
 * Describes the enum metaxisdata.v1.SyncTrigger.
 */
export declare const SyncTriggerSchema: GenEnum<SyncTrigger>;

/**
 * SyncDatabaseState is one database's outcome within a sync operation.
 *
 * @generated from enum metaxisdata.v1.SyncDatabaseState
 */
export enum SyncDatabaseState {
  /**
   * @generated from enum value: SYNC_DATABASE_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SYNC_DATABASE_STATE_SUCCEEDED = 1;
   */
  SUCCEEDED = 1,

  /**
   * @generated from enum value: SYNC_DATABASE_STATE_FAILED = 2;
   */
  FAILED = 2,

  /**
   * The operation ended before this database produced a result, because its
   * deadline passed or its instance disappeared.
   *
   * @generated from enum value: SYNC_DATABASE_STATE_UNFINISHED = 3;
   */
  UNFINISHED = 3,
}

/**
 * Describes the enum metaxisdata.v1.SyncDatabaseState.
 */
export declare const SyncDatabaseStateSchema: GenEnum<SyncDatabaseState>;

/**
 * OpenLineageFailureKind is why an OpenLineage request produced no lineage.
 *
 * @generated from enum metaxisdata.v1.OpenLineageFailureKind
 */
export enum OpenLineageFailureKind {
  /**
   * @generated from enum value: OPENLINEAGE_FAILURE_KIND_UNSPECIFIED = 0;
   */
  OPENLINEAGE_FAILURE_KIND_UNSPECIFIED = 0,

  /**
   * The event could not be parsed, or crossed a per-event limit.
   *
   * @generated from enum value: OPENLINEAGE_FAILURE_KIND_INVALID_EVENT = 1;
   */
  OPENLINEAGE_FAILURE_KIND_INVALID_EVENT = 1,

  /**
   * The request body or the batch crossed a transport limit.
   *
   * @generated from enum value: OPENLINEAGE_FAILURE_KIND_LIMIT_EXCEEDED = 2;
   */
  OPENLINEAGE_FAILURE_KIND_LIMIT_EXCEEDED = 2,

  /**
   * The event's namespace is not the one the ingestion key is scoped to.
   *
   * @generated from enum value: OPENLINEAGE_FAILURE_KIND_SCOPE_MISMATCH = 3;
   */
  OPENLINEAGE_FAILURE_KIND_SCOPE_MISMATCH = 3,

  /**
   * The event could not be persisted.
   *
   * @generated from enum value: OPENLINEAGE_FAILURE_KIND_PERSIST_FAILED = 4;
   */
  OPENLINEAGE_FAILURE_KIND_PERSIST_FAILED = 4,

  /**
   * The event was persisted but its lineage could not be derived.
   *
   * @generated from enum value: OPENLINEAGE_FAILURE_KIND_PROCESS_FAILED = 5;
   */
  OPENLINEAGE_FAILURE_KIND_PROCESS_FAILED = 5,

  /**
   * The dataset matched no registered instance and was stored as an external
   * dataset, so any lineage naming it points at something the registry does not
   * describe. Check the instance's data source host and port, or add a
   * namespace mapping.
   *
   * @generated from enum value: OPENLINEAGE_FAILURE_KIND_NAMESPACE_UNMAPPED = 6;
   */
  OPENLINEAGE_FAILURE_KIND_NAMESPACE_UNMAPPED = 6,
}

/**
 * Describes the enum metaxisdata.v1.OpenLineageFailureKind.
 */
export declare const OpenLineageFailureKindSchema: GenEnum<OpenLineageFailureKind>;

/**
 * NotificationService serves the caller's own in-app messages: the outcome of a
 * sync operation they asked for, and the ingestion failures a workspace
 * administrator needs to see.
 *
 * No method here carries a (metaxisdata.v1.permission) annotation, and none is
 * reachable without credentials. An inbox belongs to one principal, which the
 * workspace-scoped IAM catalog cannot express: every handler therefore scopes
 * its query by the authenticated caller's id, the same way UserService's
 * self-service paths do. Gating these methods on a permission instead would
 * lock a custom role out of its own messages.
 *
 * @generated from service metaxisdata.v1.NotificationService
 */
export declare const NotificationService: GenService<{
  /**
   * List the caller's notifications, newest first.
   *
   * @generated from rpc metaxisdata.v1.NotificationService.ListNotifications
   */
  listNotifications: {
    methodKind: "unary";
    input: typeof ListNotificationsRequestSchema;
    output: typeof ListNotificationsResponseSchema;
  },
  /**
   * Count the caller's unread notifications.
   *
   * @generated from rpc metaxisdata.v1.NotificationService.GetUnreadNotificationCount
   */
  getUnreadNotificationCount: {
    methodKind: "unary";
    input: typeof GetUnreadNotificationCountRequestSchema;
    output: typeof GetUnreadNotificationCountResponseSchema;
  },
  /**
   * Mark the named notifications read. Already-read notifications are left
   * alone, so the call is idempotent.
   *
   * @generated from rpc metaxisdata.v1.NotificationService.BatchMarkNotificationsRead
   */
  batchMarkNotificationsRead: {
    methodKind: "unary";
    input: typeof BatchMarkNotificationsReadRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Mark every unread notification of the caller read.
   *
   * @generated from rpc metaxisdata.v1.NotificationService.MarkAllNotificationsRead
   */
  markAllNotificationsRead: {
    methodKind: "unary";
    input: typeof MarkAllNotificationsReadRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Delete one of the caller's notifications.
   *
   * @generated from rpc metaxisdata.v1.NotificationService.DeleteNotification
   */
  deleteNotification: {
    methodKind: "unary";
    input: typeof DeleteNotificationRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Stream the caller's notifications as they are written, until the connection
   * ends or the server ends it.
   *
   * No (google.api.http) annotation: this is a server-streaming method, and the
   * REST gateway cannot carry one — it answers "streaming calls are not yet
   * supported in the in-process transport", as the generated ExplainSQL gateway
   * route does. The browser reaches the Connect endpoint directly, the way it does
   * for ExplainSQL.
   *
   * @generated from rpc metaxisdata.v1.NotificationService.SubscribeNotifications
   */
  subscribeNotifications: {
    methodKind: "server_streaming";
    input: typeof SubscribeNotificationsRequestSchema;
    output: typeof SubscribeNotificationsResponseSchema;
  },
}>;

