// @generated by protoc-gen-es v2.5.2
// @generated from file v1/setting_service.proto (package metaxisdata.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../google/api/annotations_pb";
import { file_google_api_client } from "../google/api/client_pb";
import { file_google_api_field_behavior } from "../google/api/field_behavior_pb";
import { file_google_protobuf_field_mask } from "@bufbuild/protobuf/wkt";
import { file_v1_annotation } from "./annotation_pb";

/**
 * Describes the file v1/setting_service.proto.
 */
export const file_v1_setting_service = /*@__PURE__*/
  fileDesc("Chh2MS9zZXR0aW5nX3NlcnZpY2UucHJvdG8SDm1ldGF4aXNkYXRhLnYxImoKF1dvcmtzcGFjZVByb2ZpbGVTZXR0aW5nEhQKDGV4dGVybmFsX3VybBgBIAEoCRIXCg9kaXNhbGxvd19zaWdudXAYAiABKAgSIAoYZGlzYWxsb3dfcGFzc3dvcmRfc2lnbmluGAMgASgIIiMKIUdldFdvcmtzcGFjZVByb2ZpbGVTZXR0aW5nUmVxdWVzdCKWAQokVXBkYXRlV29ya3NwYWNlUHJvZmlsZVNldHRpbmdSZXF1ZXN0Ej0KB3NldHRpbmcYASABKAsyJy5tZXRheGlzZGF0YS52MS5Xb3Jrc3BhY2VQcm9maWxlU2V0dGluZ0ID4EECEi8KC3VwZGF0ZV9tYXNrGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLkZpZWxkTWFzazKfAwoOU2V0dGluZ1NlcnZpY2USowEKGkdldFdvcmtzcGFjZVByb2ZpbGVTZXR0aW5nEjEubWV0YXhpc2RhdGEudjEuR2V0V29ya3NwYWNlUHJvZmlsZVNldHRpbmdSZXF1ZXN0GicubWV0YXhpc2RhdGEudjEuV29ya3NwYWNlUHJvZmlsZVNldHRpbmciKYDqMAGC0+STAh8SHS92MS9zZXR0aW5ncy93b3Jrc3BhY2VQcm9maWxlEuYBCh1VcGRhdGVXb3Jrc3BhY2VQcm9maWxlU2V0dGluZxI0Lm1ldGF4aXNkYXRhLnYxLlVwZGF0ZVdvcmtzcGFjZVByb2ZpbGVTZXR0aW5nUmVxdWVzdBonLm1ldGF4aXNkYXRhLnYxLldvcmtzcGFjZVByb2ZpbGVTZXR0aW5nImbaQRNzZXR0aW5nLHVwZGF0ZV9tYXNriuowGm1ldGF4aXNkYXRhLnNldHRpbmdzLndyaXRlmOowAYLT5JMCKDoHc2V0dGluZzIdL3YxL3NldHRpbmdzL3dvcmtzcGFjZVByb2ZpbGVCNlo0Z2l0aHViLmNvbS9SYW54eS9tZXRheGlzZGF0YS9iYWNrZW5kL2dlbmVyYXRlZC1nby92MWIGcHJvdG8z", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior, file_google_protobuf_field_mask, file_v1_annotation]);

/**
 * Describes the message metaxisdata.v1.WorkspaceProfileSetting.
 * Use `create(WorkspaceProfileSettingSchema)` to create a new message.
 */
export const WorkspaceProfileSettingSchema = /*@__PURE__*/
  messageDesc(file_v1_setting_service, 0);

/**
 * Describes the message metaxisdata.v1.GetWorkspaceProfileSettingRequest.
 * Use `create(GetWorkspaceProfileSettingRequestSchema)` to create a new message.
 */
export const GetWorkspaceProfileSettingRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_setting_service, 1);

/**
 * Describes the message metaxisdata.v1.UpdateWorkspaceProfileSettingRequest.
 * Use `create(UpdateWorkspaceProfileSettingRequestSchema)` to create a new message.
 */
export const UpdateWorkspaceProfileSettingRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_setting_service, 2);

/**
 * @generated from service metaxisdata.v1.SettingService
 */
export const SettingService = /*@__PURE__*/
  serviceDesc(file_v1_setting_service, 0);

