// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: store/audit_log.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditLogSeverity int32

const (
	AuditLogSeverity_AUDIT_SEVERITY_UNSPECIFIED AuditLogSeverity = 0
	AuditLogSeverity_INFO                       AuditLogSeverity = 1
	AuditLogSeverity_WARNING                    AuditLogSeverity = 2
	AuditLogSeverity_ERROR                      AuditLogSeverity = 3
)

// Enum value maps for AuditLogSeverity.
var (
	AuditLogSeverity_name = map[int32]string{
		0: "AUDIT_SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
	}
	AuditLogSeverity_value = map[string]int32{
		"AUDIT_SEVERITY_UNSPECIFIED": 0,
		"INFO":                       1,
		"WARNING":                    2,
		"ERROR":                      3,
	}
)

func (x AuditLogSeverity) Enum() *AuditLogSeverity {
	p := new(AuditLogSeverity)
	*p = x
	return p
}

func (x AuditLogSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditLogSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_store_audit_log_proto_enumTypes[0].Descriptor()
}

func (AuditLogSeverity) Type() protoreflect.EnumType {
	return &file_store_audit_log_proto_enumTypes[0]
}

func (x AuditLogSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditLogSeverity.Descriptor instead.
func (AuditLogSeverity) EnumDescriptor() ([]byte, []int) {
	return file_store_audit_log_proto_rawDescGZIP(), []int{0}
}

type AuditLogStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogStatus) Reset() {
	*x = AuditLogStatus{}
	mi := &file_store_audit_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogStatus) ProtoMessage() {}

func (x *AuditLogStatus) ProtoReflect() protoreflect.Message {
	mi := &file_store_audit_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogStatus.ProtoReflect.Descriptor instead.
func (*AuditLogStatus) Descriptor() ([]byte, []int) {
	return file_store_audit_log_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLogStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AuditLogStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuditRequestMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequestMetadata) Reset() {
	*x = AuditRequestMetadata{}
	mi := &file_store_audit_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequestMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequestMetadata) ProtoMessage() {}

func (x *AuditRequestMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_store_audit_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequestMetadata.ProtoReflect.Descriptor instead.
func (*AuditRequestMetadata) Descriptor() ([]byte, []int) {
	return file_store_audit_log_proto_rawDescGZIP(), []int{1}
}

func (x *AuditRequestMetadata) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AuditRequestMetadata) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type AuditLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The audit_log row's primary key. The public v1 AuditLog exposes it as the
	// resource name "{parent}/auditLogs/{id}" instead, because audit rows are
	// identified by an opaque server-generated id.
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Parent          string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Method          string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Resource        string                 `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	User            string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Severity        AuditLogSeverity       `protobuf:"varint,7,opt,name=severity,proto3,enum=metaxisdata.store.AuditLogSeverity" json:"severity,omitempty"`
	Request         *structpb.Struct       `protobuf:"bytes,8,opt,name=request,proto3" json:"request,omitempty"`
	Response        *structpb.Struct       `protobuf:"bytes,9,opt,name=response,proto3" json:"response,omitempty"`
	Status          *AuditLogStatus        `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs       int64                  `protobuf:"varint,11,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ServiceData     *structpb.Struct       `protobuf:"bytes,12,opt,name=service_data,json=serviceData,proto3" json:"service_data,omitempty"`
	RequestMetadata *AuditRequestMetadata  `protobuf:"bytes,13,opt,name=request_metadata,json=requestMetadata,proto3" json:"request_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_store_audit_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_store_audit_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_store_audit_log_proto_rawDescGZIP(), []int{2}
}

func (x *AuditLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuditLog) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *AuditLog) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *AuditLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuditLog) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuditLog) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AuditLog) GetSeverity() AuditLogSeverity {
	if x != nil {
		return x.Severity
	}
	return AuditLogSeverity_AUDIT_SEVERITY_UNSPECIFIED
}

func (x *AuditLog) GetRequest() *structpb.Struct {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuditLog) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AuditLog) GetStatus() *AuditLogStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AuditLog) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AuditLog) GetServiceData() *structpb.Struct {
	if x != nil {
		return x.ServiceData
	}
	return nil
}

func (x *AuditLog) GetRequestMetadata() *AuditRequestMetadata {
	if x != nil {
		return x.RequestMetadata
	}
	return nil
}

var File_store_audit_log_proto protoreflect.FileDescriptor

const file_store_audit_log_proto_rawDesc = "" +
	"\n" +
	"\x15store/audit_log.proto\x12\x11metaxisdata.store\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x0eAuditLogStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x14AuditRequestMetadata\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"\xca\x04\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12;\n" +
	"\vcreate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12?\n" +
	"\bseverity\x18\a \x01(\x0e2#.metaxisdata.store.AuditLogSeverityR\bseverity\x121\n" +
	"\arequest\x18\b \x01(\v2\x17.google.protobuf.StructR\arequest\x123\n" +
	"\bresponse\x18\t \x01(\v2\x17.google.protobuf.StructR\bresponse\x129\n" +
	"\x06status\x18\n" +
	" \x01(\v2!.metaxisdata.store.AuditLogStatusR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\v \x01(\x03R\tlatencyMs\x12:\n" +
	"\fservice_data\x18\f \x01(\v2\x17.google.protobuf.StructR\vserviceData\x12R\n" +
	"\x10request_metadata\x18\r \x01(\v2'.metaxisdata.store.AuditRequestMetadataR\x0frequestMetadata*T\n" +
	"\x10AuditLogSeverity\x12\x1e\n" +
	"\x1aAUDIT_SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03B\x14Z\x12generated-go/storeb\x06proto3"

var (
	file_store_audit_log_proto_rawDescOnce sync.Once
	file_store_audit_log_proto_rawDescData []byte
)

func file_store_audit_log_proto_rawDescGZIP() []byte {
	file_store_audit_log_proto_rawDescOnce.Do(func() {
		file_store_audit_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_audit_log_proto_rawDesc), len(file_store_audit_log_proto_rawDesc)))
	})
	return file_store_audit_log_proto_rawDescData
}

var file_store_audit_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_store_audit_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_store_audit_log_proto_goTypes = []any{
	(AuditLogSeverity)(0),         // 0: metaxisdata.store.AuditLogSeverity
	(*AuditLogStatus)(nil),        // 1: metaxisdata.store.AuditLogStatus
	(*AuditRequestMetadata)(nil),  // 2: metaxisdata.store.AuditRequestMetadata
	(*AuditLog)(nil),              // 3: metaxisdata.store.AuditLog
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_store_audit_log_proto_depIdxs = []int32{
	4, // 0: metaxisdata.store.AuditLog.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: metaxisdata.store.AuditLog.severity:type_name -> metaxisdata.store.AuditLogSeverity
	5, // 2: metaxisdata.store.AuditLog.request:type_name -> google.protobuf.Struct
	5, // 3: metaxisdata.store.AuditLog.response:type_name -> google.protobuf.Struct
	1, // 4: metaxisdata.store.AuditLog.status:type_name -> metaxisdata.store.AuditLogStatus
	5, // 5: metaxisdata.store.AuditLog.service_data:type_name -> google.protobuf.Struct
	2, // 6: metaxisdata.store.AuditLog.request_metadata:type_name -> metaxisdata.store.AuditRequestMetadata
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_store_audit_log_proto_init() }
func file_store_audit_log_proto_init() {
	if File_store_audit_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_audit_log_proto_rawDesc), len(file_store_audit_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_audit_log_proto_goTypes,
		DependencyIndexes: file_store_audit_log_proto_depIdxs,
		EnumInfos:         file_store_audit_log_proto_enumTypes,
		MessageInfos:      file_store_audit_log_proto_msgTypes,
	}.Build()
	File_store_audit_log_proto = out.File
	file_store_audit_log_proto_goTypes = nil
	file_store_audit_log_proto_depIdxs = nil
}
